import type { OTAConnection, ChannelPerformance } from '@/lib/types'

export const sampleOTAConnections: OTAConnection[] = [
  {
    id: 'conn-1',
    channel: 'booking.com',
    name: 'Booking.com',
    status: 'connected',
    apiKey: '****',
    propertyId: 'PROP123456',
    isActive: true,
    autoSync: true,
    syncFrequency: 60,
    lastSync: Date.now() - 1800000,
    nextSync: Date.now() + 1800000,
    totalBookings: 245,
    totalRevenue: 156780,
    averageRating: 8.7,
    reviewCount: 189,
    commission: 15,
    syncSettings: {
      syncAvailability: true,
      syncRates: true,
      syncRestrictions: true,
      syncInventory: true,
      syncReservations: true,
      syncReviews: true
    },
    createdAt: Date.now() - 86400000 * 180,
    updatedAt: Date.now() - 1800000,
    connectedBy: 'Admin User'
  },
  {
    id: 'conn-2',
    channel: 'agoda',
    name: 'Agoda',
    status: 'connected',
    propertyId: 'AG789012',
    isActive: true,
    autoSync: true,
    syncFrequency: 120,
    lastSync: Date.now() - 3600000,
    nextSync: Date.now() + 3600000,
    totalBookings: 178,
    totalRevenue: 98450,
    averageRating: 8.5,
    reviewCount: 142,
    commission: 18,
    syncSettings: {
      syncAvailability: true,
      syncRates: true,
      syncRestrictions: true,
      syncInventory: true,
      syncReservations: true,
      syncReviews: true
    },
    createdAt: Date.now() - 86400000 * 150,
    updatedAt: Date.now() - 3600000,
    connectedBy: 'Admin User'
  },
  {
    id: 'conn-3',
    channel: 'expedia',
    name: 'Expedia',
    status: 'connected',
    propertyId: 'EX345678',
    isActive: true,
    autoSync: true,
    syncFrequency: 90,
    lastSync: Date.now() - 2700000,
    nextSync: Date.now() + 2700000,
    totalBookings: 132,
    totalRevenue: 87340,
    averageRating: 8.3,
    reviewCount: 98,
    commission: 20,
    syncSettings: {
      syncAvailability: true,
      syncRates: true,
      syncRestrictions: true,
      syncInventory: true,
      syncReservations: true,
      syncReviews: false
    },
    createdAt: Date.now() - 86400000 * 120,
    updatedAt: Date.now() - 2700000,
    connectedBy: 'Admin User'
  },
  {
    id: 'conn-4',
    channel: 'airbnb',
    name: 'Airbnb',
    status: 'pending',
    isActive: false,
    autoSync: false,
    syncFrequency: 60,
    totalBookings: 0,
    totalRevenue: 0,
    commission: 14,
    syncSettings: {
      syncAvailability: true,
      syncRates: true,
      syncRestrictions: false,
      syncInventory: true,
      syncReservations: true,
      syncReviews: true
    },
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 7,
    connectedBy: 'Admin User'
  }
]

export const sampleChannelPerformance: ChannelPerformance[] = [
  {
    id: 'perf-1',
    channel: 'booking.com',
    period: 'monthly',
    startDate: Date.now() - 86400000 * 30,
    endDate: Date.now(),
    bookings: 45,
    cancellations: 3,
    revenue: 28950,
    commission: 4342.5,
    netRevenue: 24607.5,
    averageRoomRate: 195,
    averageLOS: 2.8,
    conversionRate: 12.5,
    reviewCount: 38,
    averageRating: 8.7,
    responseRate: 95,
    responseTime: 4.2,
    calculatedAt: Date.now()
  },
  {
    id: 'perf-2',
    channel: 'agoda',
    period: 'monthly',
    startDate: Date.now() - 86400000 * 30,
    endDate: Date.now(),
    bookings: 32,
    cancellations: 2,
    revenue: 18240,
    commission: 3283.2,
    netRevenue: 14956.8,
    averageRoomRate: 182,
    averageLOS: 2.5,
    conversionRate: 10.8,
    reviewCount: 26,
    averageRating: 8.5,
    responseRate: 88,
    responseTime: 6.5,
    calculatedAt: Date.now()
  },
  {
    id: 'perf-3',
    channel: 'expedia',
    period: 'monthly',
    startDate: Date.now() - 86400000 * 30,
    endDate: Date.now(),
    bookings: 24,
    cancellations: 4,
    revenue: 16080,
    commission: 3216,
    netRevenue: 12864,
    averageRoomRate: 201,
    averageLOS: 3.1,
    conversionRate: 8.9,
    reviewCount: 18,
    averageRating: 8.3,
    responseRate: 78,
    responseTime: 8.1,
    calculatedAt: Date.now()
  }
]
