import type {
  EmailTemplateAnalytics,
  EmailSentRecord,
  EmailCampaignAnalytics,
  EmailTrackingEvent,
  EmailTrackingLink,
} from './types'

const now = Date.now()
const oneDay = 24 * 60 * 60 * 1000
const oneWeek = 7 * oneDay
const oneMonth = 30 * oneDay

export const sampleEmailTemplateAnalytics: EmailTemplateAnalytics[] = [
  {
    templateId: 'tpl-001',
    templateName: 'Standard Guest Invoice',
    templateCategory: 'invoice',
    period: 'monthly',
    startDate: now - oneMonth,
    endDate: now,
    totalSent: 450,
    totalDelivered: 445,
    totalBounced: 5,
    totalOpened: 312,
    totalClicked: 89,
    totalComplained: 1,
    totalUnsubscribed: 2,
    uniqueOpens: 298,
    uniqueClicks: 78,
    deliveryRate: 98.89,
    openRate: 70.11,
    clickRate: 20.00,
    clickToOpenRate: 28.53,
    bounceRate: 1.11,
    complaintRate: 0.22,
    unsubscribeRate: 0.45,
    averageTimeToOpen: 7200,
    averageTimeToClick: 14400,
    topLinks: [
      { url: 'https://pay.w3hotel.com/invoice', linkText: 'Pay Now', clicks: 52, uniqueClicks: 45 },
      { url: 'https://portal.w3hotel.com/view-invoice', linkText: 'View Invoice', clicks: 28, uniqueClicks: 24 },
      { url: 'https://w3hotel.com/contact', linkText: 'Contact Us', clicks: 9, uniqueClicks: 9 },
    ],
    opensByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      opens: Math.floor(Math.random() * 20),
    })),
    clicksByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      clicks: Math.floor(Math.random() * 10),
    })),
    deviceBreakdown: {
      desktop: 180,
      mobile: 95,
      tablet: 23,
      unknown: 0,
    },
    calculatedAt: now,
  },
  {
    templateId: 'tpl-002',
    templateName: 'Batch Invoice Email',
    templateCategory: 'batch',
    period: 'monthly',
    startDate: now - oneMonth,
    endDate: now,
    totalSent: 220,
    totalDelivered: 218,
    totalBounced: 2,
    totalOpened: 164,
    totalClicked: 67,
    totalComplained: 0,
    totalUnsubscribed: 1,
    uniqueOpens: 158,
    uniqueClicks: 61,
    deliveryRate: 99.09,
    openRate: 75.23,
    clickRate: 30.73,
    clickToOpenRate: 40.85,
    bounceRate: 0.91,
    complaintRate: 0.00,
    unsubscribeRate: 0.46,
    averageTimeToOpen: 5400,
    averageTimeToClick: 10800,
    topLinks: [
      { url: 'https://pay.w3hotel.com/batch', linkText: 'Pay Multiple Invoices', clicks: 45, uniqueClicks: 40 },
      { url: 'https://portal.w3hotel.com/invoices', linkText: 'View All Invoices', clicks: 22, uniqueClicks: 21 },
    ],
    opensByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      opens: Math.floor(Math.random() * 15),
    })),
    clicksByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      clicks: Math.floor(Math.random() * 8),
    })),
    deviceBreakdown: {
      desktop: 120,
      mobile: 32,
      tablet: 6,
      unknown: 0,
    },
    calculatedAt: now,
  },
  {
    templateId: 'tpl-003',
    templateName: 'Payment Reminder',
    templateCategory: 'reminder',
    period: 'monthly',
    startDate: now - oneMonth,
    endDate: now,
    totalSent: 85,
    totalDelivered: 83,
    totalBounced: 2,
    totalOpened: 68,
    totalClicked: 41,
    totalComplained: 1,
    totalUnsubscribed: 0,
    uniqueOpens: 65,
    uniqueClicks: 38,
    deliveryRate: 97.65,
    openRate: 81.93,
    clickRate: 49.40,
    clickToOpenRate: 60.29,
    bounceRate: 2.35,
    complaintRate: 1.20,
    unsubscribeRate: 0.00,
    averageTimeToOpen: 3600,
    averageTimeToClick: 7200,
    topLinks: [
      { url: 'https://pay.w3hotel.com/pay', linkText: 'Pay Now', clicks: 38, uniqueClicks: 36 },
      { url: 'https://w3hotel.com/contact', linkText: 'Contact Us', clicks: 3, uniqueClicks: 2 },
    ],
    opensByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      opens: Math.floor(Math.random() * 5),
    })),
    clicksByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      clicks: Math.floor(Math.random() * 3),
    })),
    deviceBreakdown: {
      desktop: 45,
      mobile: 20,
      tablet: 0,
      unknown: 0,
    },
    calculatedAt: now,
  },
  {
    templateId: 'tpl-004',
    templateName: 'Booking Confirmation',
    templateCategory: 'confirmation',
    period: 'monthly',
    startDate: now - oneMonth,
    endDate: now,
    totalSent: 320,
    totalDelivered: 318,
    totalBounced: 2,
    totalOpened: 295,
    totalClicked: 156,
    totalComplained: 0,
    totalUnsubscribed: 1,
    uniqueOpens: 290,
    uniqueClicks: 148,
    deliveryRate: 99.38,
    openRate: 92.77,
    clickRate: 49.06,
    clickToOpenRate: 52.88,
    bounceRate: 0.63,
    complaintRate: 0.00,
    unsubscribeRate: 0.31,
    averageTimeToOpen: 1800,
    averageTimeToClick: 3600,
    topLinks: [
      { url: 'https://portal.w3hotel.com/booking', linkText: 'View Booking', clicks: 95, uniqueClicks: 90 },
      { url: 'https://w3hotel.com/directions', linkText: 'Get Directions', clicks: 45, uniqueClicks: 42 },
      { url: 'https://w3hotel.com/services', linkText: 'Add Services', clicks: 16, uniqueClicks: 16 },
    ],
    opensByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      opens: Math.floor(Math.random() * 18),
    })),
    clicksByHour: Array.from({ length: 24 }, (_, i) => ({
      hour: i,
      clicks: Math.floor(Math.random() * 10),
    })),
    deviceBreakdown: {
      desktop: 145,
      mobile: 125,
      tablet: 20,
      unknown: 0,
    },
    calculatedAt: now,
  },
]

export const sampleCampaignAnalytics: EmailCampaignAnalytics[] = [
  {
    batchId: 'batch-001',
    batchName: 'December Invoices',
    campaignType: 'invoice-batch',
    templateId: 'tpl-002',
    templateName: 'Batch Invoice Email',
    sentAt: now - 5 * oneDay,
    sentBy: 'user-001',
    totalRecipients: 125,
    totalSent: 125,
    totalDelivered: 124,
    totalBounced: 1,
    totalOpened: 95,
    totalClicked: 42,
    totalFailed: 0,
    deliveryRate: 99.20,
    openRate: 76.61,
    clickRate: 33.87,
    clickToOpenRate: 44.21,
    bounceRate: 0.80,
    revenue: 0,
    conversions: 38,
    conversionRate: 30.40,
    calculatedAt: now,
  },
  {
    batchId: 'batch-002',
    batchName: 'Outstanding Payment Reminders',
    campaignType: 'reminder',
    templateId: 'tpl-003',
    templateName: 'Payment Reminder',
    sentAt: now - 12 * oneDay,
    sentBy: 'user-001',
    totalRecipients: 45,
    totalSent: 45,
    totalDelivered: 44,
    totalBounced: 1,
    totalOpened: 38,
    totalClicked: 24,
    totalFailed: 0,
    deliveryRate: 97.78,
    openRate: 86.36,
    clickRate: 54.55,
    clickToOpenRate: 63.16,
    bounceRate: 2.22,
    revenue: 0,
    conversions: 18,
    conversionRate: 40.91,
    calculatedAt: now,
  },
  {
    batchId: 'batch-003',
    batchName: 'January Confirmations',
    campaignType: 'notification',
    templateId: 'tpl-004',
    templateName: 'Booking Confirmation',
    sentAt: now - 2 * oneDay,
    sentBy: 'user-002',
    totalRecipients: 78,
    totalSent: 78,
    totalDelivered: 78,
    totalBounced: 0,
    totalOpened: 72,
    totalClicked: 45,
    totalFailed: 0,
    deliveryRate: 100.00,
    openRate: 92.31,
    clickRate: 57.69,
    clickToOpenRate: 62.50,
    bounceRate: 0.00,
    revenue: 0,
    conversions: 0,
    conversionRate: 0,
    calculatedAt: now,
  },
]

export const sampleEmailSentRecords: EmailSentRecord[] = [
  {
    id: 'email-001',
    templateId: 'tpl-001',
    templateName: 'Standard Guest Invoice',
    templateCategory: 'invoice',
    recipientEmail: 'john.doe@example.com',
    recipientName: 'John Doe',
    guestId: 'guest-001',
    invoiceId: 'INV-2024-0001',
    subject: 'Your Invoice from W3 Hotel - INV-2024-0001',
    sentAt: now - 2 * oneDay,
    sentBy: 'user-001',
    status: 'delivered',
    trackingId: 'track-001',
    trackingLinks: [
      {
        id: 'link-001',
        originalUrl: 'https://pay.w3hotel.com/invoice/INV-2024-0001',
        trackingUrl: 'https://track.w3hotel.com/c/001',
        linkText: 'Pay Now',
        linkType: 'payment',
        clicks: 2,
        uniqueClicks: 1,
        firstClickAt: now - 1.5 * oneDay,
        lastClickAt: now - oneDay,
      },
      {
        id: 'link-002',
        originalUrl: 'https://portal.w3hotel.com/view-invoice/INV-2024-0001',
        trackingUrl: 'https://track.w3hotel.com/c/002',
        linkText: 'View Invoice',
        linkType: 'portal',
        clicks: 1,
        uniqueClicks: 1,
        firstClickAt: now - 1.8 * oneDay,
      },
    ],
    events: [
      {
        id: 'evt-001',
        emailSentId: 'email-001',
        eventType: 'sent',
        timestamp: now - 2 * oneDay,
        recipientEmail: 'john.doe@example.com',
      },
      {
        id: 'evt-002',
        emailSentId: 'email-001',
        eventType: 'delivered',
        timestamp: now - 2 * oneDay + 300000,
        recipientEmail: 'john.doe@example.com',
      },
      {
        id: 'evt-003',
        emailSentId: 'email-001',
        eventType: 'opened',
        timestamp: now - 1.8 * oneDay,
        recipientEmail: 'john.doe@example.com',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        ipAddress: '192.168.1.1',
      },
      {
        id: 'evt-004',
        emailSentId: 'email-001',
        eventType: 'clicked',
        timestamp: now - 1.8 * oneDay + 60000,
        recipientEmail: 'john.doe@example.com',
        linkClicked: 'https://portal.w3hotel.com/view-invoice/INV-2024-0001',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        ipAddress: '192.168.1.1',
      },
      {
        id: 'evt-005',
        emailSentId: 'email-001',
        eventType: 'clicked',
        timestamp: now - 1.5 * oneDay,
        recipientEmail: 'john.doe@example.com',
        linkClicked: 'https://pay.w3hotel.com/invoice/INV-2024-0001',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X)',
        ipAddress: '192.168.1.1',
      },
    ],
  },
]
