import { 
  type Room, 
  type Guest, 
  type Reservation,
  type Folio,
  type InventoryItem,
  type HousekeepingTask,
  type MenuItem,
  type Order,
  type Supplier,
  type Employee,
  type MaintenanceRequest,
  type FoodItem,
  type FoodSupplierMapping,
  type QualityCheck,
  type Amenity,
  type AmenityUsageLog,
  type AmenityAutoOrder,
  type ConstructionMaterial,
  type ConstructionProject,
  type Contractor,
  type GeneralProduct,
  type SystemUser,
  type ActivityLog,
  type Attendance,
  type LeaveRequest,
  type Shift,
  type DutyRoster,
  type PerformanceReview,
  type Requisition,
  type PurchaseOrder,
  type GoodsReceivedNote
} from './types'
import { getRolePermissions } from './helpers'

export const sampleGuests: Guest[] = [
  {
    id: 'guest-1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@email.com',
    phone: '+1-555-0101',
    nationality: 'USA',
    loyaltyPoints: 1200,
    totalStays: 5,
    totalSpent: 4500,
    preferences: ['Non-smoking', 'High floor', 'King bed'],
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'guest-2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@email.com',
    phone: '+1-555-0102',
    nationality: 'Canada',
    loyaltyPoints: 800,
    totalStays: 3,
    totalSpent: 2800,
    preferences: ['Pool view', 'Late checkout'],
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'guest-3',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'mchen@email.com',
    phone: '+1-555-0103',
    nationality: 'Singapore',
    loyaltyPoints: 2100,
    totalStays: 8,
    totalSpent: 7200,
    preferences: ['Extra pillows', 'Quiet room'],
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  }
]

export const sampleRooms: Room[] = [
  { id: 'room-101', roomNumber: '101', floor: 1, roomType: 'standard', status: 'vacant-clean', baseRate: 120, maxOccupancy: 2, amenities: ['WiFi', 'TV', 'AC'] },
  { id: 'room-102', roomNumber: '102', floor: 1, roomType: 'standard', status: 'occupied-clean', baseRate: 120, maxOccupancy: 2, amenities: ['WiFi', 'TV', 'AC'] },
  { id: 'room-103', roomNumber: '103', floor: 1, roomType: 'deluxe', status: 'vacant-dirty', baseRate: 180, maxOccupancy: 2, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar'] },
  { id: 'room-104', roomNumber: '104', floor: 1, roomType: 'deluxe', status: 'occupied-dirty', baseRate: 180, maxOccupancy: 2, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar'] },
  { id: 'room-201', roomNumber: '201', floor: 2, roomType: 'standard', status: 'vacant-clean', baseRate: 120, maxOccupancy: 2, amenities: ['WiFi', 'TV', 'AC'] },
  { id: 'room-202', roomNumber: '202', floor: 2, roomType: 'standard', status: 'occupied-clean', baseRate: 120, maxOccupancy: 2, amenities: ['WiFi', 'TV', 'AC'] },
  { id: 'room-203', roomNumber: '203', floor: 2, roomType: 'suite', status: 'vacant-clean', baseRate: 280, maxOccupancy: 4, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar', 'Balcony', 'Jacuzzi'] },
  { id: 'room-204', roomNumber: '204', floor: 2, roomType: 'suite', status: 'maintenance', baseRate: 280, maxOccupancy: 4, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar', 'Balcony'] },
  { id: 'room-301', roomNumber: '301', floor: 3, roomType: 'executive', status: 'vacant-clean', baseRate: 220, maxOccupancy: 3, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar', 'Work Desk'] },
  { id: 'room-302', roomNumber: '302', floor: 3, roomType: 'executive', status: 'occupied-clean', baseRate: 220, maxOccupancy: 3, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar', 'Work Desk'] },
  { id: 'room-303', roomNumber: '303', floor: 3, roomType: 'presidential', status: 'vacant-clean', baseRate: 500, maxOccupancy: 6, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar', 'Balcony', 'Jacuzzi', 'Kitchen', 'Living Room'] },
  { id: 'room-304', roomNumber: '304', floor: 3, roomType: 'deluxe', status: 'out-of-order', baseRate: 180, maxOccupancy: 2, amenities: ['WiFi', 'TV', 'AC', 'Mini Bar'] }
]

export const sampleReservations: Reservation[] = [
  {
    id: 'res-1',
    guestId: 'guest-1',
    roomId: 'room-102',
    checkInDate: Date.now() - 3 * 24 * 60 * 60 * 1000,
    checkOutDate: Date.now() - 1 * 24 * 60 * 60 * 1000,
    adults: 2,
    children: 0,
    status: 'checked-out',
    ratePerNight: 18500,
    totalAmount: 37000,
    advancePaid: 18500,
    source: 'Direct',
    specialRequests: 'High floor, non-smoking',
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    createdBy: 'user-1'
  },
  {
    id: 'res-2',
    guestId: 'guest-2',
    roomId: 'room-104',
    checkInDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
    checkOutDate: Date.now() - 2 * 24 * 60 * 60 * 1000,
    adults: 2,
    children: 1,
    status: 'checked-out',
    ratePerNight: 28000,
    totalAmount: 84000,
    advancePaid: 28000,
    source: 'Booking.com',
    specialRequests: 'Extra bed for child, pool view',
    createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    createdBy: 'user-1'
  },
  {
    id: 'res-3',
    guestId: 'guest-3',
    roomId: 'room-203',
    checkInDate: Date.now() - 7 * 24 * 60 * 60 * 1000,
    checkOutDate: Date.now() - 3 * 24 * 60 * 60 * 1000,
    adults: 2,
    children: 2,
    status: 'checked-out',
    ratePerNight: 42000,
    totalAmount: 168000,
    advancePaid: 42000,
    source: 'Website',
    specialRequests: 'Honeymoon package, late checkout',
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    createdBy: 'user-1'
  },
  {
    id: 'res-4',
    guestId: 'guest-1',
    roomId: 'room-301',
    checkInDate: Date.now() - 2 * 24 * 60 * 60 * 1000,
    checkOutDate: Date.now() + 2 * 24 * 60 * 60 * 1000,
    adults: 1,
    children: 0,
    status: 'checked-in',
    ratePerNight: 32000,
    totalAmount: 128000,
    advancePaid: 32000,
    source: 'Direct',
    specialRequests: 'Business traveler, early check-in',
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
    createdBy: 'user-1'
  },
  {
    id: 'res-5',
    guestId: 'guest-2',
    roomId: 'room-202',
    checkInDate: Date.now() - 1 * 24 * 60 * 60 * 1000,
    checkOutDate: Date.now() + 3 * 24 * 60 * 60 * 1000,
    adults: 2,
    children: 0,
    status: 'checked-in',
    ratePerNight: 18500,
    totalAmount: 74000,
    advancePaid: 18500,
    source: 'Agoda',
    specialRequests: 'Anniversary celebration',
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
    createdBy: 'user-1'
  },
  {
    id: 'res-6',
    guestId: 'guest-3',
    checkInDate: Date.now() + 5 * 24 * 60 * 60 * 1000,
    checkOutDate: Date.now() + 10 * 24 * 60 * 60 * 1000,
    adults: 3,
    children: 1,
    status: 'confirmed',
    ratePerNight: 42000,
    totalAmount: 210000,
    advancePaid: 42000,
    source: 'Website',
    specialRequests: 'Family vacation, connecting rooms if possible',
    createdAt: Date.now() - 25 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now(),
    createdBy: 'user-1'
  }
]

export const sampleFolios: Folio[] = [
  {
    id: 'folio-1',
    reservationId: 'res-1',
    guestId: 'guest-1',
    charges: [
      {
        id: 'charge-1',
        folioId: 'folio-1',
        description: 'Room Charges',
        amount: 120,
        quantity: 3,
        department: 'front-office',
        timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
        postedBy: 'system'
      }
    ],
    payments: [
      {
        id: 'payment-1',
        folioId: 'folio-1',
        amount: 120,
        method: 'card',
        status: 'paid',
        timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
        receivedBy: 'user-1'
      }
    ],
    balance: 240,
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'folio-2',
    reservationId: 'res-2',
    guestId: 'guest-2',
    charges: [
      {
        id: 'charge-2',
        folioId: 'folio-2',
        description: 'Room Charges',
        amount: 180,
        quantity: 3,
        department: 'front-office',
        timestamp: Date.now(),
        postedBy: 'system'
      },
      {
        id: 'charge-3',
        folioId: 'folio-2',
        description: 'Mini Bar',
        amount: 25,
        quantity: 1,
        department: 'fnb',
        timestamp: Date.now(),
        postedBy: 'user-1'
      }
    ],
    payments: [
      {
        id: 'payment-2',
        folioId: 'folio-2',
        amount: 180,
        method: 'card',
        status: 'paid',
        timestamp: Date.now(),
        receivedBy: 'user-1'
      }
    ],
    balance: 385,
    createdAt: Date.now(),
    updatedAt: Date.now()
  }
]

export const sampleInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Chicken Breast',
    category: 'Meat',
    unit: 'kg',
    currentStock: 25,
    reorderLevel: 15,
    reorderQuantity: 30,
    unitCost: 8.50,
    storeLocation: 'Kitchen Cold Storage',
    expiryDate: Date.now() + 5 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now()
  },
  {
    id: 'inv-2',
    name: 'Tomatoes',
    category: 'Vegetables',
    unit: 'kg',
    currentStock: 8,
    reorderLevel: 10,
    reorderQuantity: 20,
    unitCost: 3.20,
    storeLocation: 'Kitchen Pantry',
    expiryDate: Date.now() + 3 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now()
  },
  {
    id: 'inv-3',
    name: 'Olive Oil',
    category: 'Cooking Oils',
    unit: 'liter',
    currentStock: 12,
    reorderLevel: 5,
    reorderQuantity: 15,
    unitCost: 15.00,
    storeLocation: 'Kitchen Pantry',
    lastUpdated: Date.now()
  },
  {
    id: 'inv-4',
    name: 'Bed Sheets (Queen)',
    category: 'Linen',
    unit: 'set',
    currentStock: 45,
    reorderLevel: 20,
    reorderQuantity: 30,
    unitCost: 25.00,
    storeLocation: 'Housekeeping Store',
    lastUpdated: Date.now()
  },
  {
    id: 'inv-5',
    name: 'Bath Towels',
    category: 'Linen',
    unit: 'piece',
    currentStock: 120,
    reorderLevel: 50,
    reorderQuantity: 100,
    unitCost: 8.00,
    storeLocation: 'Housekeeping Store',
    lastUpdated: Date.now()
  },
  {
    id: 'inv-6',
    name: 'Shampoo Bottles',
    category: 'Amenities',
    unit: 'bottle',
    currentStock: 200,
    reorderLevel: 100,
    reorderQuantity: 300,
    unitCost: 1.50,
    storeLocation: 'Housekeeping Store',
    lastUpdated: Date.now()
  },
  {
    id: 'inv-7',
    name: 'Coffee Beans',
    category: 'Beverages',
    unit: 'kg',
    currentStock: 5,
    reorderLevel: 8,
    reorderQuantity: 15,
    unitCost: 22.00,
    storeLocation: 'Kitchen Pantry',
    expiryDate: Date.now() + 30 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now()
  },
  {
    id: 'inv-8',
    name: 'Fresh Milk',
    category: 'Dairy',
    unit: 'liter',
    currentStock: 15,
    reorderLevel: 20,
    reorderQuantity: 40,
    unitCost: 2.50,
    storeLocation: 'Kitchen Cold Storage',
    expiryDate: Date.now() + 4 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now()
  }
]

export const sampleMenuItems: MenuItem[] = [
  {
    id: 'menu-1',
    name: 'Grilled Chicken Sandwich',
    description: 'Grilled chicken breast with lettuce, tomato, and mayo',
    category: 'Mains',
    price: 15.99,
    available: true,
    preparationTime: 15
  },
  {
    id: 'menu-2',
    name: 'Caesar Salad',
    description: 'Fresh romaine lettuce with Caesar dressing and croutons',
    category: 'Salads',
    price: 12.99,
    available: true,
    preparationTime: 10
  },
  {
    id: 'menu-3',
    name: 'Club Sandwich',
    description: 'Triple decker with turkey, bacon, lettuce, and tomato',
    category: 'Mains',
    price: 14.99,
    available: true,
    preparationTime: 12
  },
  {
    id: 'menu-4',
    name: 'Cappuccino',
    description: 'Espresso with steamed milk and foam',
    category: 'Beverages',
    price: 4.99,
    available: true,
    preparationTime: 5
  },
  {
    id: 'menu-5',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice',
    category: 'Beverages',
    price: 5.99,
    available: true,
    preparationTime: 3
  }
]

export const sampleHousekeepingTasks: HousekeepingTask[] = [
  {
    id: 'hk-1',
    roomId: 'room-103',
    assignedTo: 'emp-1',
    taskType: 'clean',
    status: 'pending',
    priority: 'normal',
    createdAt: Date.now()
  },
  {
    id: 'hk-2',
    roomId: 'room-104',
    assignedTo: 'emp-1',
    taskType: 'turndown',
    status: 'pending',
    priority: 'normal',
    createdAt: Date.now()
  },
  {
    id: 'hk-3',
    roomId: 'room-203',
    taskType: 'deep-clean',
    status: 'pending',
    priority: 'high',
    createdAt: Date.now()
  }
]

export const sampleSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    supplierId: 'SUP-2024-001',
    name: 'Fresh Foods Co.',
    category: ['Food', 'Meat', 'Vegetables', 'Dairy'],
    contactPersons: [
      { id: 'cp-1', name: 'David Miller', role: 'Sales Manager', email: 'david@freshfoods.com', phone: '+1-555-0201', isPrimary: true },
      { id: 'cp-2', name: 'Sarah Jones', role: 'Account Manager', email: 'sarah@freshfoods.com', phone: '+1-555-0202', isPrimary: false }
    ],
    email: 'info@freshfoods.com',
    phone: '+1-555-0200',
    address: '123 Food Street',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    postalCode: '10001',
    taxId: 'TAX-FF-001',
    businessRegNumber: 'BRN-FF-2020',
    website: 'www.freshfoods.com',
    paymentTerms: 'Net 30',
    creditLimit: 50000,
    deliveryTimeDays: 2,
    minimumOrderValue: 500,
    rating: 4.5,
    deliveryTimeRating: 4.7,
    costRating: 4.2,
    qualityRating: 4.6,
    totalOrders: 45,
    totalSpent: 25000,
    bankName: 'City Bank',
    bankAccountNumber: '1234567890',
    bankBranch: 'Main Branch',
    notes: 'Reliable supplier for fresh produce',
    isActive: true,
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 10 * 24 * 60 * 60 * 1000
  },
  {
    id: 'sup-2',
    supplierId: 'SUP-2024-002',
    name: 'Linen Supply Inc.',
    category: ['Amenities', 'Linen', 'Cleaning'],
    contactPersons: [
      { id: 'cp-3', name: 'Emma Wilson', role: 'Director', email: 'emma@linensupply.com', phone: '+1-555-0301', isPrimary: true }
    ],
    email: 'contact@linensupply.com',
    phone: '+1-555-0300',
    address: '456 Textile Ave',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    postalCode: '90001',
    taxId: 'TAX-LS-002',
    businessRegNumber: 'BRN-LS-2019',
    website: 'www.linensupply.com',
    paymentTerms: 'Net 15',
    creditLimit: 30000,
    deliveryTimeDays: 3,
    minimumOrderValue: 300,
    rating: 4.8,
    deliveryTimeRating: 4.9,
    costRating: 4.5,
    qualityRating: 5.0,
    totalOrders: 32,
    totalSpent: 18000,
    bankName: 'West Coast Bank',
    bankAccountNumber: '0987654321',
    bankBranch: 'Downtown Branch',
    notes: 'Premium quality linens',
    isActive: true,
    createdAt: Date.now() - 150 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000
  },
  {
    id: 'sup-3',
    supplierId: 'SUP-2024-003',
    name: 'Beverage Wholesalers',
    category: ['Food', 'Beverages'],
    contactPersons: [
      { id: 'cp-4', name: 'Robert Brown', role: 'Sales Rep', email: 'robert@beveragewholesale.com', phone: '+1-555-0401', isPrimary: true }
    ],
    email: 'sales@beveragewholesale.com',
    phone: '+1-555-0400',
    address: '789 Distribution Blvd',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    postalCode: '60601',
    paymentTerms: 'Net 30',
    deliveryTimeDays: 1,
    rating: 4.2,
    deliveryTimeRating: 4.5,
    costRating: 4.0,
    qualityRating: 4.1,
    totalOrders: 28,
    totalSpent: 12000,
    isActive: true,
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 15 * 24 * 60 * 60 * 1000
  },
  {
    id: 'sup-4',
    supplierId: 'SUP-2024-004',
    name: 'Construction Materials Ltd',
    category: ['Construction', 'Maintenance', 'Hardware'],
    contactPersons: [
      { id: 'cp-5', name: 'Michael Chen', role: 'Project Manager', email: 'michael@constructionmats.com', phone: '+1-555-0501', isPrimary: true },
      { id: 'cp-6', name: 'Lisa Wang', role: 'Supply Coordinator', email: 'lisa@constructionmats.com', phone: '+1-555-0502', isPrimary: false }
    ],
    email: 'info@constructionmats.com',
    phone: '+1-555-0500',
    address: '321 Industrial Park',
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    postalCode: '77001',
    taxId: 'TAX-CM-004',
    businessRegNumber: 'BRN-CM-2018',
    website: 'www.constructionmats.com',
    paymentTerms: 'Net 45',
    creditLimit: 75000,
    deliveryTimeDays: 5,
    minimumOrderValue: 1000,
    rating: 4.4,
    deliveryTimeRating: 4.3,
    costRating: 4.6,
    qualityRating: 4.3,
    totalOrders: 18,
    totalSpent: 35000,
    bankName: 'Texas Regional Bank',
    bankAccountNumber: '1122334455',
    bankBranch: 'Industrial District',
    notes: 'Bulk construction materials supplier',
    isActive: true,
    createdAt: Date.now() - 200 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 20 * 24 * 60 * 60 * 1000
  },
  {
    id: 'sup-5',
    supplierId: 'SUP-2024-005',
    name: 'Office Essentials Corp',
    category: ['General Products', 'Office Supplies', 'Technology'],
    contactPersons: [
      { id: 'cp-7', name: 'Amanda Smith', role: 'Account Executive', email: 'amanda@officeessentials.com', phone: '+1-555-0601', isPrimary: true }
    ],
    email: 'orders@officeessentials.com',
    phone: '+1-555-0600',
    address: '555 Business Plaza',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    postalCode: '02101',
    paymentTerms: 'Net 30',
    deliveryTimeDays: 2,
    minimumOrderValue: 200,
    rating: 4.6,
    deliveryTimeRating: 4.8,
    costRating: 4.4,
    qualityRating: 4.6,
    totalOrders: 25,
    totalSpent: 8500,
    isActive: true,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000
  }
]

export const sampleEmployees: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'EMP001',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.g@hotel.com',
    phone: '+1-555-0301',
    dateOfBirth: Date.now() - 35 * 365 * 24 * 60 * 60 * 1000,
    address: '123 Oak Street, Apt 4B, New York, NY 10001',
    emergencyContactName: 'Carlos Garcia',
    emergencyContactPhone: '+1-555-0311',
    department: 'housekeeping',
    role: 'housekeeper',
    joinDate: Date.now() - 365 * 24 * 60 * 60 * 1000,
    status: 'active',
    createdAt: Date.now() - 365 * 24 * 60 * 60 * 1000
  },
  {
    id: 'emp-2',
    employeeId: 'EMP002',
    firstName: 'James',
    lastName: 'Anderson',
    email: 'james.a@hotel.com',
    phone: '+1-555-0302',
    dateOfBirth: Date.now() - 28 * 365 * 24 * 60 * 60 * 1000,
    address: '456 Elm Avenue, Brooklyn, NY 11201',
    emergencyContactName: 'Sarah Anderson',
    emergencyContactPhone: '+1-555-0312',
    department: 'front-office',
    role: 'front-desk',
    joinDate: Date.now() - 240 * 24 * 60 * 60 * 1000,
    status: 'active',
    createdAt: Date.now() - 240 * 24 * 60 * 60 * 1000
  },
  {
    id: 'emp-3',
    employeeId: 'EMP003',
    firstName: 'Sophie',
    lastName: 'Martin',
    email: 'sophie.m@hotel.com',
    phone: '+1-555-0303',
    dateOfBirth: Date.now() - 42 * 365 * 24 * 60 * 60 * 1000,
    address: '789 Pine Road, Queens, NY 11375',
    emergencyContactName: 'Pierre Martin',
    emergencyContactPhone: '+1-555-0313',
    department: 'fnb',
    role: 'chef',
    joinDate: Date.now() - 480 * 24 * 60 * 60 * 1000,
    status: 'active',
    createdAt: Date.now() - 480 * 24 * 60 * 60 * 1000
  }
]

export const sampleMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: 'maint-1',
    requestNumber: 'MR001',
    roomId: 'room-204',
    location: 'Room 204',
    issueType: 'AC Repair',
    description: 'Air conditioning not cooling properly',
    priority: 'high',
    status: 'in-progress',
    assignedTo: 'emp-4',
    reportedBy: 'emp-1',
    createdAt: Date.now() - 2 * 60 * 60 * 1000,
    scheduledAt: Date.now() - 1 * 60 * 60 * 1000,
    startedAt: Date.now() - 30 * 60 * 1000
  },
  {
    id: 'maint-2',
    requestNumber: 'MR002',
    roomId: 'room-304',
    location: 'Room 304',
    issueType: 'Plumbing',
    description: 'Leaking faucet in bathroom',
    priority: 'urgent',
    status: 'scheduled',
    reportedBy: 'emp-2',
    createdAt: Date.now() - 3 * 60 * 60 * 1000,
    scheduledAt: Date.now() + 1 * 60 * 60 * 1000
  }
]

export const sampleFoodItems: FoodItem[] = [
  {
    id: 'food-1',
    foodId: 'F001',
    name: 'Fresh Tomatoes',
    category: 'vegetables',
    unit: 'kg',
    currentStock: 12,
    reorderLevel: 15,
    reorderQuantity: 30,
    unitCost: 3.50,
    supplierIds: ['sup-1'],
    orderFrequency: 'daily',
    storeLocation: 'Kitchen Cold Storage',
    expiryDate: Date.now() + 3 * 24 * 60 * 60 * 1000,
    batchNumber: 'VEG2024011',
    qualityStatus: 'good',
    receivedDate: Date.now() - 1 * 24 * 60 * 60 * 1000,
    isPerishable: true,
    shelfLife: 5,
    lastOrdered: Date.now() - 1 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-2',
    foodId: 'F002',
    name: 'Onions',
    category: 'vegetables',
    unit: 'kg',
    currentStock: 25,
    reorderLevel: 20,
    reorderQuantity: 40,
    unitCost: 2.20,
    supplierIds: ['sup-1'],
    orderFrequency: 'weekly',
    storeLocation: 'Kitchen Dry Storage',
    expiryDate: Date.now() + 14 * 24 * 60 * 60 * 1000,
    batchNumber: 'VEG2024012',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 2 * 24 * 60 * 60 * 1000,
    isPerishable: true,
    shelfLife: 21,
    lastOrdered: Date.now() - 7 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-3',
    foodId: 'F003',
    name: 'Fresh Chicken Breast',
    category: 'meat',
    unit: 'kg',
    currentStock: 8,
    reorderLevel: 15,
    reorderQuantity: 30,
    unitCost: 9.50,
    supplierIds: ['sup-1'],
    orderFrequency: 'daily',
    storeLocation: 'Kitchen Cold Storage - Meat',
    expiryDate: Date.now() + 2 * 24 * 60 * 60 * 1000,
    batchNumber: 'MEAT2024015',
    qualityStatus: 'excellent',
    receivedDate: Date.now(),
    isPerishable: true,
    shelfLife: 3,
    lastOrdered: Date.now(),
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-4',
    foodId: 'F004',
    name: 'Fresh Milk (Full Cream)',
    category: 'dairy',
    unit: 'liter',
    currentStock: 18,
    reorderLevel: 25,
    reorderQuantity: 50,
    unitCost: 2.80,
    supplierIds: ['sup-1', 'sup-3'],
    orderFrequency: 'daily',
    storeLocation: 'Kitchen Refrigerator',
    expiryDate: Date.now() + 5 * 24 * 60 * 60 * 1000,
    batchNumber: 'DAIRY2024021',
    qualityStatus: 'excellent',
    receivedDate: Date.now(),
    isPerishable: true,
    shelfLife: 7,
    lastOrdered: Date.now(),
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-5',
    foodId: 'F005',
    name: 'Basmati Rice (Premium)',
    category: 'dry-goods',
    unit: 'kg',
    currentStock: 45,
    reorderLevel: 30,
    reorderQuantity: 100,
    unitCost: 4.20,
    supplierIds: ['sup-1'],
    orderFrequency: 'monthly',
    storeLocation: 'Kitchen Dry Storage',
    batchNumber: 'RICE2024003',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 10 * 24 * 60 * 60 * 1000,
    isPerishable: false,
    lastOrdered: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-6',
    foodId: 'F006',
    name: 'Extra Virgin Olive Oil',
    category: 'non-perishable',
    unit: 'liter',
    currentStock: 15,
    reorderLevel: 10,
    reorderQuantity: 24,
    unitCost: 16.50,
    supplierIds: ['sup-1'],
    orderFrequency: 'monthly',
    storeLocation: 'Kitchen Pantry',
    batchNumber: 'OIL2024008',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 15 * 24 * 60 * 60 * 1000,
    isPerishable: false,
    lastOrdered: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-7',
    foodId: 'F007',
    name: 'Orange Juice (Fresh)',
    category: 'beverage',
    unit: 'liter',
    currentStock: 8,
    reorderLevel: 12,
    reorderQuantity: 24,
    unitCost: 5.50,
    supplierIds: ['sup-3'],
    orderFrequency: 'daily',
    storeLocation: 'Bar Refrigerator',
    expiryDate: Date.now() + 4 * 24 * 60 * 60 * 1000,
    batchNumber: 'BEV2024032',
    qualityStatus: 'good',
    receivedDate: Date.now(),
    isPerishable: true,
    shelfLife: 5,
    lastOrdered: Date.now(),
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-8',
    foodId: 'F008',
    name: 'Black Pepper (Whole)',
    category: 'spices',
    unit: 'kg',
    currentStock: 3.5,
    reorderLevel: 2,
    reorderQuantity: 5,
    unitCost: 28.00,
    supplierIds: ['sup-1'],
    orderFrequency: 'monthly',
    storeLocation: 'Kitchen Spice Rack',
    batchNumber: 'SPICE2024019',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 20 * 24 * 60 * 60 * 1000,
    isPerishable: false,
    lastOrdered: Date.now() - 60 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-9',
    foodId: 'F009',
    name: 'Frozen French Fries',
    category: 'frozen',
    unit: 'kg',
    currentStock: 22,
    reorderLevel: 15,
    reorderQuantity: 40,
    unitCost: 3.80,
    supplierIds: ['sup-1'],
    orderFrequency: 'weekly',
    storeLocation: 'Kitchen Freezer A',
    expiryDate: Date.now() + 180 * 24 * 60 * 60 * 1000,
    batchNumber: 'FROZEN2024044',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
    isPerishable: true,
    shelfLife: 365,
    lastOrdered: Date.now() - 14 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-10',
    foodId: 'F010',
    name: 'Fresh Salmon Fillet',
    category: 'meat',
    unit: 'kg',
    currentStock: 5,
    reorderLevel: 8,
    reorderQuantity: 15,
    unitCost: 18.50,
    supplierIds: ['sup-1'],
    orderFrequency: 'weekly',
    storeLocation: 'Kitchen Cold Storage - Seafood',
    expiryDate: Date.now() + 2 * 24 * 60 * 60 * 1000,
    batchNumber: 'FISH2024011',
    qualityStatus: 'excellent',
    receivedDate: Date.now(),
    isPerishable: true,
    shelfLife: 2,
    lastOrdered: Date.now(),
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-11',
    foodId: 'F011',
    name: 'Fresh Strawberries',
    category: 'fruits',
    unit: 'kg',
    currentStock: 6,
    reorderLevel: 10,
    reorderQuantity: 15,
    unitCost: 8.50,
    supplierIds: ['sup-1'],
    orderFrequency: 'daily',
    storeLocation: 'Kitchen Cold Storage',
    expiryDate: Date.now() + 3 * 24 * 60 * 60 * 1000,
    batchNumber: 'FRUIT2024028',
    qualityStatus: 'good',
    receivedDate: Date.now(),
    isPerishable: true,
    shelfLife: 5,
    lastOrdered: Date.now(),
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-12',
    foodId: 'F012',
    name: 'Fresh Bread Rolls',
    category: 'bakery',
    unit: 'piece',
    currentStock: 85,
    reorderLevel: 100,
    reorderQuantity: 200,
    unitCost: 0.45,
    supplierIds: ['sup-1'],
    orderFrequency: 'daily',
    storeLocation: 'Kitchen Bakery Section',
    expiryDate: Date.now() + 1 * 24 * 60 * 60 * 1000,
    batchNumber: 'BAKERY2024056',
    qualityStatus: 'excellent',
    receivedDate: Date.now(),
    isPerishable: true,
    shelfLife: 2,
    lastOrdered: Date.now(),
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-13',
    foodId: 'F013',
    name: 'Cheddar Cheese',
    category: 'dairy',
    unit: 'kg',
    currentStock: 7,
    reorderLevel: 10,
    reorderQuantity: 20,
    unitCost: 12.50,
    supplierIds: ['sup-1'],
    orderFrequency: 'weekly',
    storeLocation: 'Kitchen Refrigerator',
    expiryDate: Date.now() + 21 * 24 * 60 * 60 * 1000,
    batchNumber: 'DAIRY2024019',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 3 * 24 * 60 * 60 * 1000,
    isPerishable: true,
    shelfLife: 30,
    lastOrdered: Date.now() - 7 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-14',
    foodId: 'F014',
    name: 'Champagne (Premium)',
    category: 'beverage',
    unit: 'bottle',
    currentStock: 24,
    reorderLevel: 12,
    reorderQuantity: 36,
    unitCost: 45.00,
    supplierIds: ['sup-3'],
    orderFrequency: 'on-demand',
    storeLocation: 'Wine Cellar',
    batchNumber: 'WINE2024007',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 30 * 24 * 60 * 60 * 1000,
    isPerishable: false,
    lastOrdered: Date.now() - 60 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'food-15',
    foodId: 'F015',
    name: 'All-Purpose Flour',
    category: 'dry-goods',
    unit: 'kg',
    currentStock: 55,
    reorderLevel: 40,
    reorderQuantity: 100,
    unitCost: 1.80,
    supplierIds: ['sup-1'],
    orderFrequency: 'monthly',
    storeLocation: 'Kitchen Dry Storage',
    batchNumber: 'FLOUR2024005',
    qualityStatus: 'excellent',
    receivedDate: Date.now() - 10 * 24 * 60 * 60 * 1000,
    isPerishable: false,
    lastOrdered: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000
  }
]

export const sampleFoodSupplierMappings: FoodSupplierMapping[] = [
  {
    id: 'fsm-1',
    foodItemId: 'food-1',
    supplierId: 'sup-1',
    isPrimary: true,
    unitPrice: 3.50,
    minimumOrderQuantity: 20,
    leadTimeDays: 1,
    qualityRating: 4.5,
    lastSupplyDate: Date.now() - 1 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'fsm-2',
    foodItemId: 'food-4',
    supplierId: 'sup-1',
    isPrimary: true,
    unitPrice: 2.80,
    minimumOrderQuantity: 30,
    leadTimeDays: 1,
    qualityRating: 4.8,
    lastSupplyDate: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'fsm-3',
    foodItemId: 'food-4',
    supplierId: 'sup-3',
    isPrimary: false,
    unitPrice: 2.95,
    minimumOrderQuantity: 25,
    leadTimeDays: 1,
    qualityRating: 4.3,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'fsm-4',
    foodItemId: 'food-7',
    supplierId: 'sup-3',
    isPrimary: true,
    unitPrice: 5.50,
    minimumOrderQuantity: 20,
    leadTimeDays: 1,
    qualityRating: 4.6,
    lastSupplyDate: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  }
]

export const sampleQualityChecks: QualityCheck[] = [
  {
    id: 'qc-1',
    foodItemId: 'food-3',
    batchNumber: 'MEAT2024015',
    checkDate: Date.now(),
    checkedBy: 'emp-3',
    qualityStatus: 'excellent',
    temperature: 2.5,
    appearance: 'Fresh pink color, no discoloration',
    smell: 'No off odors',
    texture: 'Firm and moist',
    overallNotes: 'Meets all quality standards',
    passed: true
  },
  {
    id: 'qc-2',
    foodItemId: 'food-1',
    batchNumber: 'VEG2024011',
    checkDate: Date.now() - 1 * 24 * 60 * 60 * 1000,
    checkedBy: 'emp-3',
    qualityStatus: 'good',
    appearance: 'Slightly soft but acceptable',
    smell: 'Fresh',
    overallNotes: 'Use within 3 days',
    passed: true
  },
  {
    id: 'qc-3',
    foodItemId: 'food-10',
    batchNumber: 'FISH2024011',
    checkDate: Date.now(),
    checkedBy: 'emp-3',
    qualityStatus: 'excellent',
    temperature: 1.8,
    appearance: 'Bright orange-pink color, firm flesh',
    smell: 'Fresh ocean scent',
    texture: 'Firm and elastic',
    overallNotes: 'Premium quality salmon',
    passed: true
  }
]

export const sampleAmenities: Amenity[] = [
  {
    id: 'amenity-1',
    amenityId: 'AM001',
    name: 'Shampoo Bottles (50ml)',
    category: 'toiletries',
    department: ['housekeeping'],
    unit: 'bottle',
    currentStock: 450,
    reorderLevel: 200,
    reorderQuantity: 500,
    unitCost: 1.20,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Main Storeroom - Shelf A3',
    parLevel: 600,
    usageRatePerDay: 45,
    lastOrdered: Date.now() - 15 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 5 * 24 * 60 * 60 * 1000,
    notes: 'Guest room amenity - premium brand',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-2',
    amenityId: 'AM002',
    name: 'Conditioner Bottles (50ml)',
    category: 'toiletries',
    department: ['housekeeping'],
    unit: 'bottle',
    currentStock: 380,
    reorderLevel: 200,
    reorderQuantity: 500,
    unitCost: 1.30,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Main Storeroom - Shelf A3',
    parLevel: 600,
    usageRatePerDay: 45,
    lastOrdered: Date.now() - 15 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 5 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-3',
    amenityId: 'AM003',
    name: 'Body Wash (50ml)',
    category: 'toiletries',
    department: ['housekeeping'],
    unit: 'bottle',
    currentStock: 175,
    reorderLevel: 200,
    reorderQuantity: 500,
    unitCost: 1.40,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Main Storeroom - Shelf A3',
    parLevel: 600,
    usageRatePerDay: 45,
    lastOrdered: Date.now() - 15 * 24 * 60 * 60 * 1000,
    notes: 'LOW STOCK - Auto reorder triggered',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-4',
    amenityId: 'AM004',
    name: 'Bath Towels (White)',
    category: 'linens',
    department: ['housekeeping', 'laundry'],
    unit: 'piece',
    currentStock: 280,
    reorderLevel: 150,
    reorderQuantity: 200,
    unitCost: 8.50,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Linen Room - Rack B',
    parLevel: 400,
    usageRatePerDay: 35,
    lastOrdered: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 10 * 24 * 60 * 60 * 1000,
    notes: 'Premium Egyptian cotton',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-5',
    amenityId: 'AM005',
    name: 'Hand Towels (White)',
    category: 'linens',
    department: ['housekeeping', 'laundry'],
    unit: 'piece',
    currentStock: 425,
    reorderLevel: 200,
    reorderQuantity: 300,
    unitCost: 4.20,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Linen Room - Rack B',
    parLevel: 600,
    usageRatePerDay: 50,
    lastOrdered: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 10 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-6',
    amenityId: 'AM006',
    name: 'Bed Sheets (Queen)',
    category: 'linens',
    department: ['housekeeping', 'laundry'],
    unit: 'set',
    currentStock: 95,
    reorderLevel: 80,
    reorderQuantity: 100,
    unitCost: 22.00,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Linen Room - Rack A',
    parLevel: 200,
    usageRatePerDay: 15,
    lastOrdered: Date.now() - 45 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 20 * 24 * 60 * 60 * 1000,
    notes: '300 thread count',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-7',
    amenityId: 'AM007',
    name: 'Multi-Surface Cleaner',
    category: 'cleaning-supplies',
    department: ['housekeeping', 'public-areas'],
    unit: 'liter',
    currentStock: 42,
    reorderLevel: 30,
    reorderQuantity: 60,
    unitCost: 5.80,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Housekeeping Supply Room',
    parLevel: 80,
    usageRatePerDay: 8,
    lastOrdered: Date.now() - 20 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 8 * 24 * 60 * 60 * 1000,
    notes: 'Eco-friendly formula',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-8',
    amenityId: 'AM008',
    name: 'Bathroom Cleaner',
    category: 'cleaning-supplies',
    department: ['housekeeping'],
    unit: 'liter',
    currentStock: 28,
    reorderLevel: 25,
    reorderQuantity: 50,
    unitCost: 6.50,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Housekeeping Supply Room',
    parLevel: 70,
    usageRatePerDay: 7,
    lastOrdered: Date.now() - 20 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 8 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-9',
    amenityId: 'AM009',
    name: 'Vacuum Bags',
    category: 'cleaning-supplies',
    department: ['housekeeping', 'public-areas'],
    unit: 'piece',
    currentStock: 38,
    reorderLevel: 20,
    reorderQuantity: 40,
    unitCost: 3.20,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Housekeeping Supply Room',
    parLevel: 60,
    usageRatePerDay: 3,
    lastOrdered: Date.now() - 25 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 12 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 150 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-10',
    amenityId: 'AM010',
    name: 'Coffee Sachets (Premium)',
    category: 'beverages',
    department: ['housekeeping', 'fnb'],
    unit: 'sachet',
    currentStock: 1250,
    reorderLevel: 500,
    reorderQuantity: 1000,
    unitCost: 0.45,
    supplierIds: ['sup-1'],
    autoReorder: true,
    storeLocation: 'F&B Store - Shelf D2',
    parLevel: 2000,
    usageRatePerDay: 120,
    lastOrdered: Date.now() - 10 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 3 * 24 * 60 * 60 * 1000,
    notes: 'In-room amenity',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-11',
    amenityId: 'AM011',
    name: 'Tea Bags (Assorted)',
    category: 'beverages',
    department: ['housekeeping', 'fnb'],
    unit: 'bag',
    currentStock: 1850,
    reorderLevel: 800,
    reorderQuantity: 1500,
    unitCost: 0.25,
    supplierIds: ['sup-1'],
    autoReorder: true,
    storeLocation: 'F&B Store - Shelf D2',
    parLevel: 2500,
    usageRatePerDay: 150,
    lastOrdered: Date.now() - 10 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 3 * 24 * 60 * 60 * 1000,
    notes: 'In-room amenity - 4 varieties',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-12',
    amenityId: 'AM012',
    name: 'Sugar Sachets',
    category: 'food-items',
    department: ['housekeeping', 'fnb'],
    unit: 'sachet',
    currentStock: 450,
    reorderLevel: 500,
    reorderQuantity: 1000,
    unitCost: 0.08,
    supplierIds: ['sup-1'],
    autoReorder: true,
    storeLocation: 'F&B Store - Shelf D3',
    parLevel: 1500,
    usageRatePerDay: 180,
    notes: 'LOW STOCK - Auto reorder triggered',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-13',
    amenityId: 'AM013',
    name: 'Napkins (Paper)',
    category: 'paper-products',
    department: ['fnb', 'housekeeping'],
    unit: 'pack',
    currentStock: 155,
    reorderLevel: 100,
    reorderQuantity: 200,
    unitCost: 2.50,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'F&B Store - Shelf E1',
    parLevel: 300,
    usageRatePerDay: 25,
    lastOrdered: Date.now() - 12 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 4 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-14',
    amenityId: 'AM014',
    name: 'Toilet Paper Rolls',
    category: 'paper-products',
    department: ['housekeeping', 'public-areas'],
    unit: 'roll',
    currentStock: 680,
    reorderLevel: 400,
    reorderQuantity: 800,
    unitCost: 0.85,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Main Storeroom - Shelf C1',
    parLevel: 1200,
    usageRatePerDay: 80,
    lastOrdered: Date.now() - 18 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 6 * 24 * 60 * 60 * 1000,
    notes: 'Premium 3-ply',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 150 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-15',
    amenityId: 'AM015',
    name: 'Facial Tissue Boxes',
    category: 'paper-products',
    department: ['housekeeping'],
    unit: 'box',
    currentStock: 220,
    reorderLevel: 150,
    reorderQuantity: 250,
    unitCost: 1.80,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Main Storeroom - Shelf C2',
    parLevel: 400,
    usageRatePerDay: 30,
    lastOrdered: Date.now() - 16 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 5 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-16',
    amenityId: 'AM016',
    name: 'Laundry Detergent (Industrial)',
    category: 'laundry-supplies',
    department: ['laundry'],
    unit: 'liter',
    currentStock: 85,
    reorderLevel: 60,
    reorderQuantity: 100,
    unitCost: 12.50,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Laundry Room Storage',
    parLevel: 150,
    usageRatePerDay: 12,
    lastOrdered: Date.now() - 22 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 9 * 24 * 60 * 60 * 1000,
    notes: 'Commercial grade',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-17',
    amenityId: 'AM017',
    name: 'Fabric Softener',
    category: 'laundry-supplies',
    department: ['laundry'],
    unit: 'liter',
    currentStock: 48,
    reorderLevel: 40,
    reorderQuantity: 80,
    unitCost: 8.80,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Laundry Room Storage',
    parLevel: 120,
    usageRatePerDay: 8,
    lastOrdered: Date.now() - 22 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 9 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-18',
    amenityId: 'AM018',
    name: 'Drinking Glasses',
    category: 'room-supplies',
    department: ['housekeeping'],
    unit: 'piece',
    currentStock: 52,
    reorderLevel: 50,
    reorderQuantity: 100,
    unitCost: 2.80,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Main Storeroom - Shelf F3',
    parLevel: 150,
    usageRatePerDay: 5,
    notes: 'Replacement for breakage',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-19',
    amenityId: 'AM019',
    name: 'Slippers (Disposable)',
    category: 'guest-amenities',
    department: ['housekeeping'],
    unit: 'pair',
    currentStock: 385,
    reorderLevel: 250,
    reorderQuantity: 500,
    unitCost: 1.50,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Main Storeroom - Shelf A4',
    parLevel: 750,
    usageRatePerDay: 40,
    lastOrdered: Date.now() - 14 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 5 * 24 * 60 * 60 * 1000,
    notes: 'Guest room amenity',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  },
  {
    id: 'amenity-20',
    amenityId: 'AM020',
    name: 'Air Freshener Spray',
    category: 'public-area-supplies',
    department: ['housekeeping', 'public-areas'],
    unit: 'can',
    currentStock: 18,
    reorderLevel: 20,
    reorderQuantity: 40,
    unitCost: 4.20,
    supplierIds: ['sup-2'],
    autoReorder: true,
    storeLocation: 'Housekeeping Supply Room',
    parLevel: 60,
    usageRatePerDay: 4,
    notes: 'LOW STOCK - Auto reorder triggered',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000
  }
]

export const sampleAmenityUsageLogs: AmenityUsageLog[] = [
  {
    id: 'log-1',
    amenityId: 'amenity-1',
    department: 'housekeeping',
    quantity: 15,
    usedBy: 'emp-4',
    roomNumber: '301-315',
    purpose: 'Room restocking',
    timestamp: Date.now() - 2 * 60 * 60 * 1000
  },
  {
    id: 'log-2',
    amenityId: 'amenity-4',
    department: 'housekeeping',
    quantity: 25,
    usedBy: 'emp-4',
    roomNumber: '201-212',
    purpose: 'Daily turnover',
    timestamp: Date.now() - 4 * 60 * 60 * 1000
  },
  {
    id: 'log-3',
    amenityId: 'amenity-14',
    department: 'public-areas',
    quantity: 12,
    usedBy: 'emp-5',
    purpose: 'Lobby restroom restocking',
    timestamp: Date.now() - 1 * 60 * 60 * 1000
  }
]

export const sampleAmenityAutoOrders: AmenityAutoOrder[] = [
  {
    id: 'auto-1',
    amenityId: 'amenity-3',
    supplierId: 'sup-2',
    orderQuantity: 500,
    status: 'pending',
    triggeredAt: Date.now() - 30 * 60 * 1000
  },
  {
    id: 'auto-2',
    amenityId: 'amenity-12',
    supplierId: 'sup-1',
    orderQuantity: 1000,
    status: 'pending',
    triggeredAt: Date.now() - 15 * 60 * 1000
  },
  {
    id: 'auto-3',
    amenityId: 'amenity-20',
    supplierId: 'sup-2',
    orderQuantity: 40,
    status: 'ordered',
    triggeredAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    orderedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    orderReference: 'PO-2024-0542'
  }
]

export const sampleConstructionMaterials: ConstructionMaterial[] = [
  {
    id: 'mat-1',
    materialId: 'MAT-001',
    name: 'LED Bulbs 15W',
    category: 'electrical',
    unit: 'pcs',
    currentStock: 45,
    reorderLevel: 50,
    reorderQuantity: 100,
    unitCost: 5.50,
    supplierIds: ['sup-3'],
    segment: 'regular-maintenance',
    storeLocation: 'Electrical Storage - A1',
    warrantyMonths: 24,
    specifications: 'E27 base, warm white 3000K',
    lastOrdered: Date.now() - 15 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 10 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'mat-2',
    materialId: 'MAT-002',
    name: 'PVC Pipes 2 inch',
    category: 'plumbing',
    unit: 'meters',
    currentStock: 25,
    reorderLevel: 30,
    reorderQuantity: 50,
    unitCost: 12.75,
    supplierIds: ['sup-4'],
    segment: 'regular-maintenance',
    storeLocation: 'Plumbing Yard - B2',
    specifications: 'Schedule 40, pressure rated',
    lastOrdered: Date.now() - 20 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 15 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 200 * 24 * 60 * 60 * 1000
  },
  {
    id: 'mat-3',
    materialId: 'MAT-003',
    name: 'Wood Planks - Oak',
    category: 'carpentry',
    unit: 'sqft',
    currentStock: 120,
    reorderLevel: 100,
    reorderQuantity: 200,
    unitCost: 8.50,
    supplierIds: ['sup-5'],
    segment: 'project-construction',
    storeLocation: 'Carpentry Workshop - C1',
    projectId: 'prj-1',
    specifications: '1x6 inch, kiln dried',
    lastOrdered: Date.now() - 5 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 3 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000
  },
  {
    id: 'mat-4',
    materialId: 'MAT-004',
    name: 'Interior Paint - White',
    category: 'painting',
    unit: 'gallons',
    currentStock: 8,
    reorderLevel: 15,
    reorderQuantity: 30,
    unitCost: 35.00,
    supplierIds: ['sup-6'],
    segment: 'regular-maintenance',
    storeLocation: 'Paint Storage - D3',
    specifications: 'Semi-gloss, washable, low VOC',
    notes: 'Running low - needs reorder',
    lastOrdered: Date.now() - 45 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 40 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 365 * 24 * 60 * 60 * 1000
  },
  {
    id: 'mat-5',
    materialId: 'MAT-005',
    name: 'Circuit Breakers 20A',
    category: 'electrical',
    unit: 'pcs',
    currentStock: 0,
    reorderLevel: 10,
    reorderQuantity: 25,
    unitCost: 18.50,
    supplierIds: ['sup-3'],
    segment: 'emergency-stock',
    storeLocation: 'Electrical Storage - A2',
    warrantyMonths: 60,
    specifications: 'Single pole, 120V rated',
    notes: 'URGENT - Out of stock!',
    lastOrdered: Date.now() - 60 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 55 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 400 * 24 * 60 * 60 * 1000
  },
  {
    id: 'mat-6',
    materialId: 'MAT-006',
    name: 'HVAC Filters 20x20',
    category: 'hvac',
    unit: 'pcs',
    currentStock: 18,
    reorderLevel: 20,
    reorderQuantity: 50,
    unitCost: 22.00,
    supplierIds: ['sup-7'],
    segment: 'regular-maintenance',
    storeLocation: 'HVAC Storage - E1',
    specifications: 'MERV 13, pleated',
    lastOrdered: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 25 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 250 * 24 * 60 * 60 * 1000
  },
  {
    id: 'mat-7',
    materialId: 'MAT-007',
    name: 'Cement - Portland',
    category: 'masonry',
    unit: 'bags',
    currentStock: 40,
    reorderLevel: 20,
    reorderQuantity: 50,
    unitCost: 12.00,
    supplierIds: ['sup-8'],
    segment: 'project-construction',
    storeLocation: 'Outdoor Storage - F1',
    projectId: 'prj-2',
    specifications: '50kg bags, Type I',
    lastOrdered: Date.now() - 10 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 8 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000
  },
  {
    id: 'mat-8',
    materialId: 'MAT-008',
    name: 'Safety Goggles',
    category: 'safety-equipment',
    unit: 'pcs',
    currentStock: 25,
    reorderLevel: 15,
    reorderQuantity: 30,
    unitCost: 8.50,
    supplierIds: ['sup-9'],
    segment: 'regular-maintenance',
    storeLocation: 'Safety Equipment - G1',
    specifications: 'Anti-fog, UV protection, ANSI Z87.1',
    lastOrdered: Date.now() - 90 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 85 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 500 * 24 * 60 * 60 * 1000
  }
]

export const sampleConstructionProjects: ConstructionProject[] = [
  {
    id: 'prj-1',
    projectId: 'PRJ-2024-001',
    name: 'Presidential Suite Renovation',
    description: 'Complete renovation of room 303 including flooring, furniture, and bathroom upgrades',
    type: 'renovation',
    status: 'in-progress',
    priority: 'high',
    location: 'Room 303 - 3rd Floor',
    startDate: Date.now() - 15 * 24 * 60 * 60 * 1000,
    endDate: Date.now() + 15 * 24 * 60 * 60 * 1000,
    estimatedBudget: 45000,
    actualCost: 28500,
    completionPercentage: 60,
    assignedContractor: 'con-1',
    projectManager: 'emp-1',
    materials: [
      {
        id: 'prm-1',
        materialId: 'mat-3',
        materialName: 'Wood Planks - Oak',
        requiredQuantity: 200,
        allocatedQuantity: 200,
        usedQuantity: 120,
        unit: 'sqft',
        estimatedCost: 1700,
        actualCost: 1700
      },
      {
        id: 'prm-2',
        materialId: 'mat-4',
        materialName: 'Interior Paint - White',
        requiredQuantity: 15,
        allocatedQuantity: 15,
        usedQuantity: 8,
        unit: 'gallons',
        estimatedCost: 525,
        actualCost: 525
      }
    ],
    tasks: [
      {
        id: 'tsk-1',
        projectId: 'prj-1',
        taskName: 'Remove old flooring',
        status: 'completed',
        priority: 'high',
        assignedTo: 'con-1',
        completedAt: Date.now() - 12 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-2',
        projectId: 'prj-1',
        taskName: 'Install new oak flooring',
        status: 'in-progress',
        priority: 'high',
        assignedTo: 'con-1',
        dueDate: Date.now() + 3 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-3',
        projectId: 'prj-1',
        taskName: 'Paint walls and ceiling',
        status: 'not-started',
        priority: 'medium',
        assignedTo: 'con-1',
        dueDate: Date.now() + 8 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-4',
        projectId: 'prj-1',
        taskName: 'Install new bathroom fixtures',
        status: 'not-started',
        priority: 'high',
        dueDate: Date.now() + 12 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-5',
        projectId: 'prj-1',
        taskName: 'Final inspection and cleanup',
        status: 'not-started',
        priority: 'medium',
        dueDate: Date.now() + 15 * 24 * 60 * 60 * 1000
      }
    ],
    notes: 'High-priority renovation for VIP guests. Ensure premium materials used.',
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'prj-2',
    projectId: 'PRJ-2024-002',
    name: 'Parking Lot Expansion',
    description: 'Add 20 additional parking spaces with proper drainage and lighting',
    type: 'new-construction',
    status: 'approved',
    priority: 'medium',
    location: 'North Parking Area',
    startDate: Date.now() + 7 * 24 * 60 * 60 * 1000,
    endDate: Date.now() + 45 * 24 * 60 * 60 * 1000,
    estimatedBudget: 75000,
    actualCost: 5000,
    completionPercentage: 0,
    assignedContractor: 'con-2',
    projectManager: 'emp-2',
    materials: [
      {
        id: 'prm-3',
        materialId: 'mat-7',
        materialName: 'Cement - Portland',
        requiredQuantity: 100,
        allocatedQuantity: 50,
        usedQuantity: 0,
        unit: 'bags',
        estimatedCost: 1200,
        actualCost: 600
      }
    ],
    tasks: [
      {
        id: 'tsk-6',
        projectId: 'prj-2',
        taskName: 'Site preparation and excavation',
        status: 'not-started',
        priority: 'high',
        dueDate: Date.now() + 14 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-7',
        projectId: 'prj-2',
        taskName: 'Install drainage system',
        status: 'not-started',
        priority: 'high',
        dueDate: Date.now() + 21 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-8',
        projectId: 'prj-2',
        taskName: 'Pour concrete base',
        status: 'not-started',
        priority: 'high',
        dueDate: Date.now() + 28 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-9',
        projectId: 'prj-2',
        taskName: 'Install lighting',
        status: 'not-started',
        priority: 'medium',
        dueDate: Date.now() + 38 * 24 * 60 * 60 * 1000
      }
    ],
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'prj-3',
    projectId: 'PRJ-2024-003',
    name: 'HVAC System Upgrade',
    description: 'Replace aging HVAC units on floors 1 and 2 with energy-efficient models',
    type: 'upgrade',
    status: 'planning',
    priority: 'high',
    location: 'Floors 1 & 2',
    estimatedBudget: 125000,
    actualCost: 0,
    completionPercentage: 0,
    projectManager: 'emp-3',
    materials: [],
    tasks: [
      {
        id: 'tsk-10',
        projectId: 'prj-3',
        taskName: 'Conduct energy audit',
        status: 'in-progress',
        priority: 'high'
      },
      {
        id: 'tsk-11',
        projectId: 'prj-3',
        taskName: 'Obtain equipment quotes',
        status: 'not-started',
        priority: 'high'
      },
      {
        id: 'tsk-12',
        projectId: 'prj-3',
        taskName: 'Schedule installation windows',
        status: 'not-started',
        priority: 'medium'
      }
    ],
    notes: 'Need to coordinate with guest occupancy to minimize disruption',
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'prj-4',
    projectId: 'PRJ-2024-004',
    name: 'Pool Equipment Repair',
    description: 'Repair filtration system and resurface pool tiles',
    type: 'repair',
    status: 'completed',
    priority: 'urgent',
    location: 'Pool Area',
    startDate: Date.now() - 30 * 24 * 60 * 60 * 1000,
    endDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
    estimatedBudget: 15000,
    actualCost: 16200,
    completionPercentage: 100,
    assignedContractor: 'con-3',
    projectManager: 'emp-1',
    materials: [],
    tasks: [
      {
        id: 'tsk-13',
        projectId: 'prj-4',
        taskName: 'Diagnose filtration issue',
        status: 'completed',
        priority: 'urgent',
        completedAt: Date.now() - 28 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-14',
        projectId: 'prj-4',
        taskName: 'Replace filtration pump',
        status: 'completed',
        priority: 'urgent',
        completedAt: Date.now() - 20 * 24 * 60 * 60 * 1000
      },
      {
        id: 'tsk-15',
        projectId: 'prj-4',
        taskName: 'Resurface damaged tiles',
        status: 'completed',
        priority: 'high',
        completedAt: Date.now() - 10 * 24 * 60 * 60 * 1000
      }
    ],
    notes: 'Project went slightly over budget due to unexpected pump damage',
    createdAt: Date.now() - 35 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000
  }
]

export const sampleContractors: Contractor[] = [
  {
    id: 'con-1',
    contractorId: 'CON-001',
    name: 'Premier Renovations Inc',
    contactPerson: 'Robert Martinez',
    email: 'robert@premierreno.com',
    phone: '+1-555-0201',
    address: '456 Construction Ave, Building City, BC 12345',
    specializations: ['carpentry', 'painting', 'general-building'],
    licenseNumber: 'LIC-CAR-2024-4567',
    rating: 4.8,
    totalProjects: 12,
    totalSpent: 285000,
    paymentTerms: 'Net 30',
    insuranceExpiry: Date.now() + 365 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 730 * 24 * 60 * 60 * 1000
  },
  {
    id: 'con-2',
    contractorId: 'CON-002',
    name: 'BuildRight Construction',
    contactPerson: 'Lisa Thompson',
    email: 'lisa@buildr ight.com',
    phone: '+1-555-0202',
    address: '789 Builder Lane, Construction Town, CT 67890',
    specializations: ['masonry', 'general-building'],
    licenseNumber: 'LIC-MAS-2024-8901',
    rating: 4.5,
    totalProjects: 8,
    totalSpent: 420000,
    paymentTerms: 'Net 30',
    insuranceExpiry: Date.now() + 450 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 500 * 24 * 60 * 60 * 1000
  },
  {
    id: 'con-3',
    contractorId: 'CON-003',
    name: 'ElectroTech Solutions',
    contactPerson: 'David Kim',
    email: 'david@electrotech.com',
    phone: '+1-555-0203',
    address: '321 Electric Blvd, Tech City, TC 11223',
    specializations: ['electrical', 'hvac'],
    licenseNumber: 'LIC-ELC-2024-2345',
    rating: 4.9,
    totalProjects: 15,
    totalSpent: 195000,
    paymentTerms: 'Net 15',
    insuranceExpiry: Date.now() + 200 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 600 * 24 * 60 * 60 * 1000
  },
  {
    id: 'con-4',
    contractorId: 'CON-004',
    name: 'FlowMaster Plumbing',
    contactPerson: 'Maria Garcia',
    email: 'maria@flowmaster.com',
    phone: '+1-555-0204',
    address: '654 Pipe Street, Water City, WC 33445',
    specializations: ['plumbing'],
    licenseNumber: 'LIC-PLM-2024-6789',
    rating: 4.7,
    totalProjects: 10,
    totalSpent: 125000,
    paymentTerms: 'Net 30',
    insuranceExpiry: Date.now() + 300 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 400 * 24 * 60 * 60 * 1000
  }
]

export const sampleGeneralProducts: GeneralProduct[] = [
  {
    id: 'gp-1',
    productId: 'GP-2024-001',
    name: 'A4 Printing Paper (Ream)',
    category: 'office-supplies',
    description: 'High quality white A4 paper, 500 sheets per ream',
    unit: 'ream',
    currentStock: 45,
    reorderLevel: 20,
    reorderQuantity: 50,
    unitCost: 4.99,
    supplierIds: ['sup-5'],
    department: ['admin', 'front-office', 'finance'],
    storeLocation: 'Office Supply Room A',
    isConsumable: true,
    lastOrdered: Date.now() - 15 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 10 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-2',
    productId: 'GP-2024-002',
    name: 'All-Purpose Cleaner Spray',
    category: 'cleaning-products',
    description: 'Multi-surface cleaning spray, eco-friendly formula',
    unit: 'bottle',
    currentStock: 12,
    reorderLevel: 15,
    reorderQuantity: 30,
    unitCost: 6.50,
    supplierIds: ['sup-2'],
    department: ['housekeeping'],
    storeLocation: 'Housekeeping Supply Closet',
    isConsumable: true,
    lastOrdered: Date.now() - 20 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 18 * 24 * 60 * 60 * 1000,
    notes: 'Low stock - reorder soon',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 150 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-3',
    productId: 'GP-2024-003',
    name: 'Holiday Decoration Set',
    category: 'seasonal-items',
    description: 'Complete Christmas decoration package',
    unit: 'set',
    currentStock: 3,
    reorderLevel: 2,
    reorderQuantity: 5,
    unitCost: 299.99,
    supplierIds: ['sup-5'],
    department: ['admin'],
    storeLocation: 'Seasonal Storage Room',
    isConsumable: false,
    purchaseDate: Date.now() - 365 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 400 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-4',
    productId: 'GP-2024-004',
    name: 'Staff Uniform - Reception',
    category: 'uniforms',
    description: 'Professional reception uniform set (shirt, pants, tie)',
    unit: 'set',
    currentStock: 18,
    reorderLevel: 10,
    reorderQuantity: 15,
    unitCost: 85.00,
    supplierIds: ['sup-5'],
    department: ['front-office', 'hr'],
    storeLocation: 'Uniform Storage',
    isConsumable: false,
    warrantyMonths: 12,
    lastOrdered: Date.now() - 90 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 85 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 200 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-5',
    productId: 'GP-2024-005',
    name: 'Fire Extinguisher - ABC Type',
    category: 'safety-equipment',
    description: '5kg ABC dry powder fire extinguisher',
    unit: 'unit',
    currentStock: 25,
    reorderLevel: 10,
    reorderQuantity: 15,
    unitCost: 45.00,
    supplierIds: ['sup-4'],
    department: ['engineering'],
    storeLocation: 'Safety Equipment Room',
    isConsumable: false,
    warrantyMonths: 60,
    purchaseDate: Date.now() - 180 * 24 * 60 * 60 * 1000,
    notes: 'Annual inspection required',
    lastUpdated: Date.now(),
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-6',
    productId: 'GP-2024-006',
    name: 'Desktop Computer - Dell OptiPlex',
    category: 'technology',
    description: 'Business desktop computer with monitor, keyboard, mouse',
    unit: 'unit',
    currentStock: 8,
    reorderLevel: 3,
    reorderQuantity: 5,
    unitCost: 899.00,
    supplierIds: ['sup-5'],
    department: ['admin', 'front-office', 'finance'],
    storeLocation: 'IT Equipment Storage',
    isConsumable: false,
    warrantyMonths: 36,
    purchaseDate: Date.now() - 120 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-7',
    productId: 'GP-2024-007',
    name: 'Lobby Signage Board',
    category: 'signage',
    description: 'Digital display board for lobby announcements',
    unit: 'unit',
    currentStock: 2,
    reorderLevel: 1,
    reorderQuantity: 2,
    unitCost: 1250.00,
    supplierIds: ['sup-5'],
    department: ['front-office'],
    storeLocation: 'Equipment Storage',
    isConsumable: false,
    warrantyMonths: 24,
    purchaseDate: Date.now() - 60 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-8',
    productId: 'GP-2024-008',
    name: 'Ballpoint Pens (Box of 50)',
    category: 'office-supplies',
    description: 'Blue ink ballpoint pens',
    unit: 'box',
    currentStock: 8,
    reorderLevel: 5,
    reorderQuantity: 10,
    unitCost: 12.99,
    supplierIds: ['sup-5'],
    department: ['admin', 'front-office', 'finance', 'hr'],
    storeLocation: 'Office Supply Room A',
    isConsumable: true,
    lastOrdered: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 25 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 200 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-9',
    productId: 'GP-2024-009',
    name: 'Promotional Brochure Holder',
    category: 'promotional-materials',
    description: 'Acrylic brochure display stand',
    unit: 'unit',
    currentStock: 15,
    reorderLevel: 8,
    reorderQuantity: 12,
    unitCost: 22.50,
    supplierIds: ['sup-5'],
    department: ['front-office'],
    storeLocation: 'Marketing Materials Storage',
    isConsumable: false,
    lastOrdered: Date.now() - 45 * 24 * 60 * 60 * 1000,
    lastRestocked: Date.now() - 40 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 100 * 24 * 60 * 60 * 1000
  },
  {
    id: 'gp-10',
    productId: 'GP-2024-010',
    name: 'Reception Desk Chair',
    category: 'furniture',
    description: 'Ergonomic office chair with lumbar support',
    unit: 'unit',
    currentStock: 4,
    reorderLevel: 2,
    reorderQuantity: 3,
    unitCost: 275.00,
    supplierIds: ['sup-5'],
    department: ['front-office'],
    storeLocation: 'Furniture Storage',
    isConsumable: false,
    warrantyMonths: 24,
    purchaseDate: Date.now() - 90 * 24 * 60 * 60 * 1000,
    lastUpdated: Date.now(),
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000
  }
]

export const sampleSystemUsers: SystemUser[] = [
  {
    id: 'user-1',
    userId: 'USR-00001',
    username: 'admin',
    email: 'admin@w3hotel.com',
    firstName: 'System',
    lastName: 'Administrator',
    phone: '+1-555-1000',
    role: 'admin',
    department: 'admin',
    permissions: getRolePermissions('admin'),
    isActive: true,
    lastLogin: Date.now() - 2 * 60 * 60 * 1000,
    createdAt: Date.now() - 365 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-2',
    userId: 'USR-00002',
    username: 'procurement.manager',
    email: 'procurement@w3hotel.com',
    firstName: 'Maria',
    lastName: 'Garcia',
    phone: '+1-555-1001',
    role: 'procurement-manager',
    department: 'admin',
    permissions: getRolePermissions('procurement-manager'),
    isActive: true,
    lastLogin: Date.now() - 5 * 60 * 60 * 1000,
    createdAt: Date.now() - 300 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-3',
    userId: 'USR-00003',
    username: 'kitchen.head',
    email: 'kitchen.head@w3hotel.com',
    firstName: 'James',
    lastName: 'Wilson',
    phone: '+1-555-1002',
    role: 'department-head',
    department: 'kitchen',
    permissions: getRolePermissions('department-head'),
    isActive: true,
    lastLogin: Date.now() - 1 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 250 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-4',
    userId: 'USR-00004',
    username: 'storekeeper',
    email: 'storekeeper@w3hotel.com',
    firstName: 'David',
    lastName: 'Lee',
    phone: '+1-555-1003',
    role: 'storekeeper',
    department: 'admin',
    permissions: getRolePermissions('storekeeper'),
    isActive: true,
    lastLogin: Date.now() - 3 * 60 * 60 * 1000,
    createdAt: Date.now() - 280 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-5',
    userId: 'USR-00005',
    username: 'accounts.manager',
    email: 'accounts@w3hotel.com',
    firstName: 'Emily',
    lastName: 'Brown',
    phone: '+1-555-1004',
    role: 'accounts',
    department: 'finance',
    permissions: getRolePermissions('accounts'),
    isActive: true,
    lastLogin: Date.now() - 6 * 60 * 60 * 1000,
    createdAt: Date.now() - 320 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-6',
    userId: 'USR-00006',
    username: 'housekeeping.head',
    email: 'housekeeping.head@w3hotel.com',
    firstName: 'Sarah',
    lastName: 'Martinez',
    phone: '+1-555-1005',
    role: 'department-head',
    department: 'housekeeping',
    permissions: getRolePermissions('department-head'),
    isActive: true,
    lastLogin: Date.now() - 4 * 60 * 60 * 1000,
    createdAt: Date.now() - 260 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-7',
    userId: 'USR-00007',
    username: 'fnb.supervisor',
    email: 'fnb.supervisor@w3hotel.com',
    firstName: 'Robert',
    lastName: 'Taylor',
    phone: '+1-555-1006',
    role: 'user-requester',
    department: 'fnb',
    permissions: getRolePermissions('user-requester'),
    isActive: true,
    lastLogin: Date.now() - 8 * 60 * 60 * 1000,
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-8',
    userId: 'USR-00008',
    username: 'maintenance.engineer',
    email: 'maintenance@w3hotel.com',
    firstName: 'Michael',
    lastName: 'Anderson',
    phone: '+1-555-1007',
    role: 'user-requester',
    department: 'engineering',
    permissions: getRolePermissions('user-requester'),
    isActive: true,
    lastLogin: Date.now() - 12 * 60 * 60 * 1000,
    createdAt: Date.now() - 200 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-9',
    userId: 'USR-00009',
    username: 'front.desk',
    email: 'frontdesk@w3hotel.com',
    firstName: 'Jessica',
    lastName: 'White',
    phone: '+1-555-1008',
    role: 'user-requester',
    department: 'front-office',
    permissions: getRolePermissions('user-requester'),
    isActive: true,
    lastLogin: Date.now() - 1 * 60 * 60 * 1000,
    createdAt: Date.now() - 150 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now()
  },
  {
    id: 'user-10',
    userId: 'USR-00010',
    username: 'hr.manager',
    email: 'hr@w3hotel.com',
    firstName: 'Daniel',
    lastName: 'Kim',
    phone: '+1-555-1009',
    role: 'department-head',
    department: 'hr',
    permissions: getRolePermissions('department-head'),
    isActive: false,
    lastLogin: Date.now() - 30 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 340 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 15 * 24 * 60 * 60 * 1000
  }
]

export const sampleActivityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    userId: 'user-1',
    username: 'admin',
    userRole: 'admin',
    activityType: 'user-login',
    action: 'User logged in',
    details: 'Login successful',
    timestamp: Date.now() - 2 * 60 * 60 * 1000
  },
  {
    id: 'log-2',
    userId: 'user-2',
    username: 'procurement.manager',
    userRole: 'procurement-manager',
    activityType: 'po-created',
    action: 'Created purchase order',
    details: 'Purchase order for fresh vegetables',
    resource: 'purchase-orders',
    resourceId: 'PO-2024-001',
    timestamp: Date.now() - 5 * 60 * 60 * 1000
  },
  {
    id: 'log-3',
    userId: 'user-3',
    username: 'kitchen.head',
    userRole: 'department-head',
    activityType: 'requisition-created',
    action: 'Created internal requisition',
    details: 'Request for cooking oil and spices',
    resource: 'requisitions',
    resourceId: 'REQ-2024-045',
    timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000
  },
  {
    id: 'log-4',
    userId: 'user-2',
    username: 'procurement.manager',
    userRole: 'procurement-manager',
    activityType: 'requisition-approved',
    action: 'Approved requisition',
    details: 'Approved kitchen requisition REQ-2024-045',
    resource: 'requisitions',
    resourceId: 'REQ-2024-045',
    timestamp: Date.now() - 23 * 60 * 60 * 1000
  },
  {
    id: 'log-5',
    userId: 'user-4',
    username: 'storekeeper',
    userRole: 'storekeeper',
    activityType: 'stock-received',
    action: 'Received stock delivery',
    details: 'Received 100kg fresh vegetables from supplier',
    resource: 'stock',
    timestamp: Date.now() - 3 * 60 * 60 * 1000
  },
  {
    id: 'log-6',
    userId: 'user-5',
    username: 'accounts.manager',
    userRole: 'accounts',
    activityType: 'payment-processed',
    action: 'Processed supplier payment',
    details: 'Payment of $2,450.00 to Green Valley Farms',
    resource: 'payments',
    resourceId: 'PAY-2024-089',
    timestamp: Date.now() - 6 * 60 * 60 * 1000
  },
  {
    id: 'log-7',
    userId: 'user-1',
    username: 'admin',
    userRole: 'admin',
    activityType: 'supplier-created',
    action: 'Added new supplier',
    details: 'Created supplier: Premium Linen Co.',
    resource: 'suppliers',
    resourceId: 'sup-10',
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000
  },
  {
    id: 'log-8',
    userId: 'user-6',
    username: 'housekeeping.head',
    userRole: 'department-head',
    activityType: 'requisition-created',
    action: 'Created internal requisition',
    details: 'Request for cleaning supplies and linens',
    resource: 'requisitions',
    resourceId: 'REQ-2024-046',
    timestamp: Date.now() - 18 * 60 * 60 * 1000
  },
  {
    id: 'log-9',
    userId: 'user-4',
    username: 'storekeeper',
    userRole: 'storekeeper',
    activityType: 'stock-adjusted',
    action: 'Adjusted stock levels',
    details: 'Stock count adjustment for toiletries',
    resource: 'stock',
    timestamp: Date.now() - 12 * 60 * 60 * 1000
  },
  {
    id: 'log-10',
    userId: 'user-2',
    username: 'procurement.manager',
    userRole: 'procurement-manager',
    activityType: 'po-approved',
    action: 'Approved purchase order',
    details: 'PO for construction materials approved',
    resource: 'purchase-orders',
    resourceId: 'PO-2024-002',
    timestamp: Date.now() - 8 * 60 * 60 * 1000
  }
]

export const sampleAttendance: Attendance[] = [
  {
    id: 'att-1',
    employeeId: 'emp-1',
    date: Date.now() - 24 * 60 * 60 * 1000,
    checkIn: Date.now() - 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000,
    checkOut: Date.now() - 24 * 60 * 60 * 1000 + 17 * 60 * 60 * 1000,
    status: 'present'
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    date: Date.now() - 24 * 60 * 60 * 1000,
    checkIn: Date.now() - 24 * 60 * 60 * 1000 + 9 * 60 * 60 * 1000,
    checkOut: Date.now() - 24 * 60 * 60 * 1000 + 18 * 60 * 60 * 1000,
    status: 'present'
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    date: Date.now() - 24 * 60 * 60 * 1000,
    checkIn: Date.now() - 24 * 60 * 60 * 1000 + 7 * 60 * 60 * 1000,
    checkOut: Date.now() - 24 * 60 * 60 * 1000 + 15 * 60 * 60 * 1000,
    status: 'present'
  },
  {
    id: 'att-4',
    employeeId: 'emp-1',
    date: Date.now() - 2 * 24 * 60 * 60 * 1000,
    status: 'leave',
    notes: 'Sick leave'
  }
]

export const sampleLeaveRequests: LeaveRequest[] = [
  {
    id: 'leave-1',
    employeeId: 'emp-1',
    leaveType: 'sick',
    startDate: Date.now() - 2 * 24 * 60 * 60 * 1000,
    endDate: Date.now() - 2 * 24 * 60 * 60 * 1000,
    days: 1,
    reason: 'Flu symptoms',
    status: 'approved',
    approvedBy: 'emp-2',
    approvedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000
  },
  {
    id: 'leave-2',
    employeeId: 'emp-2',
    leaveType: 'annual',
    startDate: Date.now() + 14 * 24 * 60 * 60 * 1000,
    endDate: Date.now() + 18 * 24 * 60 * 60 * 1000,
    days: 5,
    reason: 'Family vacation',
    status: 'pending',
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000
  },
  {
    id: 'leave-3',
    employeeId: 'emp-3',
    leaveType: 'casual',
    startDate: Date.now() + 7 * 24 * 60 * 60 * 1000,
    endDate: Date.now() + 7 * 24 * 60 * 60 * 1000,
    days: 1,
    reason: 'Personal appointment',
    status: 'approved',
    approvedBy: 'emp-2',
    approvedAt: Date.now() - 30 * 60 * 1000,
    createdAt: Date.now() - 2 * 60 * 60 * 1000
  }
]

export const sampleShifts: Shift[] = [
  {
    id: 'shift-1',
    shiftType: 'morning',
    startTime: '06:00',
    endTime: '14:00',
    department: 'housekeeping',
    requiredStaff: 8,
    breakDuration: 30,
    description: 'Morning housekeeping shift for room cleaning'
  },
  {
    id: 'shift-2',
    shiftType: 'afternoon',
    startTime: '14:00',
    endTime: '22:00',
    department: 'housekeeping',
    requiredStaff: 5,
    breakDuration: 30,
    description: 'Afternoon housekeeping shift'
  },
  {
    id: 'shift-3',
    shiftType: 'full-day',
    startTime: '09:00',
    endTime: '18:00',
    department: 'front-office',
    requiredStaff: 3,
    breakDuration: 60,
    description: 'Front desk day shift'
  },
  {
    id: 'shift-4',
    shiftType: 'night',
    startTime: '22:00',
    endTime: '06:00',
    department: 'front-office',
    requiredStaff: 2,
    breakDuration: 30,
    description: 'Night reception shift'
  },
  {
    id: 'shift-5',
    shiftType: 'morning',
    startTime: '06:00',
    endTime: '14:00',
    department: 'kitchen',
    requiredStaff: 6,
    breakDuration: 30,
    description: 'Breakfast and lunch prep'
  },
  {
    id: 'shift-6',
    shiftType: 'afternoon',
    startTime: '14:00',
    endTime: '22:00',
    department: 'kitchen',
    requiredStaff: 7,
    breakDuration: 30,
    description: 'Dinner service shift'
  },
  {
    id: 'shift-7',
    shiftType: 'full-day',
    startTime: '08:00',
    endTime: '17:00',
    department: 'engineering',
    requiredStaff: 3,
    breakDuration: 60,
    description: 'Maintenance and engineering shift'
  }
]

export const sampleDutyRosters: DutyRoster[] = [
  {
    id: 'roster-1',
    employeeId: 'emp-1',
    date: Date.now(),
    shiftId: 'shift-1',
    department: 'housekeeping',
    status: 'scheduled',
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    createdBy: 'emp-2'
  },
  {
    id: 'roster-2',
    employeeId: 'emp-2',
    date: Date.now(),
    shiftId: 'shift-3',
    department: 'front-office',
    status: 'scheduled',
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    createdBy: 'emp-2'
  },
  {
    id: 'roster-3',
    employeeId: 'emp-3',
    date: Date.now(),
    shiftId: 'shift-5',
    department: 'kitchen',
    status: 'scheduled',
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    createdBy: 'emp-2'
  },
  {
    id: 'roster-4',
    employeeId: 'emp-1',
    date: Date.now() - 24 * 60 * 60 * 1000,
    shiftId: 'shift-1',
    department: 'housekeeping',
    status: 'completed',
    createdAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
    createdBy: 'emp-2'
  }
]

export const samplePerformanceReviews: PerformanceReview[] = [
  {
    id: 'review-1',
    employeeId: 'emp-1',
    reviewerId: 'emp-2',
    reviewPeriodStart: Date.now() - 180 * 24 * 60 * 60 * 1000,
    reviewPeriodEnd: Date.now() - 1 * 24 * 60 * 60 * 1000,
    punctuality: 5,
    qualityOfWork: 4,
    teamwork: 5,
    communication: 4,
    initiative: 4,
    overallRating: 4.4,
    strengths: 'Excellent time management and reliability. Very thorough in room cleaning. Great team player.',
    areasForImprovement: 'Could improve communication with front desk regarding room status updates.',
    goals: 'Complete advanced housekeeping training. Mentor new team members.',
    comments: 'Maria has been a valuable member of the housekeeping team. Consistently delivers high-quality work.',
    status: 'acknowledged',
    submittedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    acknowledgedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000
  },
  {
    id: 'review-2',
    employeeId: 'emp-3',
    reviewerId: 'emp-2',
    reviewPeriodStart: Date.now() - 180 * 24 * 60 * 60 * 1000,
    reviewPeriodEnd: Date.now() - 1 * 24 * 60 * 60 * 1000,
    punctuality: 5,
    qualityOfWork: 5,
    teamwork: 5,
    communication: 5,
    initiative: 5,
    overallRating: 5.0,
    strengths: 'Outstanding culinary skills and creativity. Excellent leadership in the kitchen. Proactive in menu development.',
    areasForImprovement: 'None identified this period. Continue excellent work.',
    goals: 'Develop seasonal menu. Train junior chefs in advanced techniques.',
    comments: 'Sophie consistently exceeds expectations and is a key asset to our culinary team.',
    status: 'submitted',
    submittedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000
  },
  {
    id: 'review-3',
    employeeId: 'emp-2',
    reviewerId: 'user-1',
    reviewPeriodStart: Date.now() - 180 * 24 * 60 * 60 * 1000,
    reviewPeriodEnd: Date.now() - 1 * 24 * 60 * 60 * 1000,
    punctuality: 5,
    qualityOfWork: 4,
    teamwork: 4,
    communication: 5,
    initiative: 4,
    overallRating: 4.4,
    strengths: 'Excellent guest relations skills. Professional demeanor. Handles difficult situations well.',
    areasForImprovement: 'Could improve technical system proficiency with new PMS software.',
    goals: 'Complete PMS advanced training. Achieve 95% guest satisfaction score.',
    comments: 'James is professional and reliable. Guests consistently praise his service.',
    status: 'draft',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000
  }
]

export const sampleOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'ORD-100001',
    type: 'dine-in',
    tableNumber: '12',
    items: [
      {
        id: 'oi-1',
        menuItemId: 'menu-1',
        name: 'Grilled Salmon',
        quantity: 2,
        price: 24.99,
        status: 'served'
      },
      {
        id: 'oi-2',
        menuItemId: 'menu-4',
        name: 'Cappuccino',
        quantity: 2,
        price: 4.99,
        status: 'served'
      }
    ],
    subtotal: 59.96,
    tax: 5.996,
    total: 65.96,
    status: 'served',
    paymentStatus: 'paid',
    createdAt: Date.now() - 3 * 60 * 60 * 1000,
    createdBy: 'user-1',
    completedAt: Date.now() - 2 * 60 * 60 * 1000
  },
  {
    id: 'order-2',
    orderNumber: 'ORD-100002',
    type: 'room-service',
    guestId: 'guest-1',
    roomId: 'room-102',
    items: [
      {
        id: 'oi-3',
        menuItemId: 'menu-2',
        name: 'Caesar Salad',
        quantity: 1,
        price: 12.99,
        status: 'preparing'
      },
      {
        id: 'oi-4',
        menuItemId: 'menu-5',
        name: 'Fresh Orange Juice',
        quantity: 1,
        price: 5.99,
        status: 'preparing'
      }
    ],
    subtotal: 18.98,
    tax: 1.898,
    total: 20.88,
    status: 'preparing',
    paymentStatus: 'pending',
    notes: 'Please deliver to room 102 at 2 PM',
    createdAt: Date.now() - 30 * 60 * 1000,
    createdBy: 'user-1'
  },
  {
    id: 'order-3',
    orderNumber: 'ORD-100003',
    type: 'dine-in',
    tableNumber: '8',
    items: [
      {
        id: 'oi-5',
        menuItemId: 'menu-3',
        name: 'Club Sandwich',
        quantity: 1,
        price: 14.99,
        status: 'ready'
      },
      {
        id: 'oi-6',
        menuItemId: 'menu-4',
        name: 'Cappuccino',
        quantity: 1,
        price: 4.99,
        status: 'ready'
      }
    ],
    subtotal: 19.98,
    tax: 1.998,
    total: 21.98,
    status: 'ready',
    paymentStatus: 'pending',
    createdAt: Date.now() - 15 * 60 * 1000,
    createdBy: 'user-1'
  },
  {
    id: 'order-4',
    orderNumber: 'ORD-100004',
    type: 'takeaway',
    items: [
      {
        id: 'oi-7',
        menuItemId: 'menu-1',
        name: 'Grilled Salmon',
        quantity: 3,
        price: 24.99,
        status: 'pending'
      },
      {
        id: 'oi-8',
        menuItemId: 'menu-2',
        name: 'Caesar Salad',
        quantity: 2,
        price: 12.99,
        status: 'pending'
      }
    ],
    subtotal: 100.95,
    tax: 10.095,
    total: 111.05,
    status: 'pending',
    paymentStatus: 'pending',
    notes: 'Extra dressing on the side',
    createdAt: Date.now() - 5 * 60 * 1000,
    createdBy: 'user-1'
  },
  {
    id: 'order-5',
    orderNumber: 'ORD-100005',
    type: 'room-service',
    guestId: 'guest-2',
    roomId: 'room-202',
    items: [
      {
        id: 'oi-9',
        menuItemId: 'menu-4',
        name: 'Cappuccino',
        quantity: 2,
        price: 4.99,
        status: 'served'
      },
      {
        id: 'oi-10',
        menuItemId: 'menu-3',
        name: 'Club Sandwich',
        quantity: 2,
        price: 14.99,
        status: 'served'
      }
    ],
    subtotal: 39.96,
    tax: 3.996,
    total: 43.96,
    status: 'served',
    paymentStatus: 'paid',
    createdAt: Date.now() - 4 * 60 * 60 * 1000,
    createdBy: 'user-1',
    completedAt: Date.now() - 3 * 60 * 60 * 1000
  }
]

export const sampleRequisitions: Requisition[] = [
  {
    id: 'req-1',
    requisitionNumber: 'REQ17345678ABCD',
    department: 'housekeeping',
    requestedBy: 'maria_garcia',
    items: [
      {
        id: 'reqitem-1',
        inventoryItemId: 'amenity-1',
        name: 'Shampoo Bottles',
        quantity: 100,
        unit: 'bottles',
        unitPrice: 3.5,
        estimatedCost: 350,
        supplierId: 'sup-1'
      },
      {
        id: 'reqitem-2',
        inventoryItemId: 'amenity-2',
        name: 'Bath Towels',
        quantity: 50,
        unit: 'pieces',
        unitPrice: 12,
        estimatedCost: 600,
        supplierId: 'sup-2'
      }
    ],
    status: 'pending-approval',
    priority: 'normal',
    notes: 'Regular monthly restock for guest rooms',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000
  },
  {
    id: 'req-2',
    requisitionNumber: 'REQ17345679EFGH',
    department: 'kitchen',
    requestedBy: 'sophie_chen',
    items: [
      {
        id: 'reqitem-3',
        inventoryItemId: 'food-1',
        name: 'Chicken Breast',
        quantity: 50,
        unit: 'kg',
        unitPrice: 8,
        estimatedCost: 400,
        supplierId: 'sup-3'
      },
      {
        id: 'reqitem-4',
        inventoryItemId: 'food-2',
        name: 'Fresh Vegetables',
        quantity: 30,
        unit: 'kg',
        unitPrice: 4.5,
        estimatedCost: 135
      }
    ],
    status: 'approved',
    priority: 'high',
    notes: 'For weekend banquet event',
    approvedBy: 'admin',
    approvedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000
  }
]

export const samplePurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-1',
    poNumber: 'PO17345680IJKL',
    supplierId: 'sup-1',
    items: [
      {
        id: 'poitem-1',
        inventoryItemId: 'food-1',
        name: 'Chicken Breast',
        quantity: 50,
        unit: 'kg',
        unitPrice: 8.5,
        total: 425
      },
      {
        id: 'poitem-2',
        inventoryItemId: 'food-2',
        name: 'Fresh Vegetables',
        quantity: 30,
        unit: 'kg',
        unitPrice: 4.75,
        total: 142.5
      }
    ],
    subtotal: 567.5,
    tax: 56.75,
    total: 624.25,
    status: 'ordered',
    expectedDelivery: Date.now() + 2 * 24 * 60 * 60 * 1000,
    notes: 'Deliver to kitchen entrance',
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    createdBy: 'admin',
    approvedBy: 'admin',
    approvedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    revisionNumber: 1,
    watermark: 'ORDERED',
    qrCode: 'QR-PO17345680IJKL',
    sentAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    sentBy: 'admin',
    emailedTo: ['supplier@example.com'],
    emailedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    auditLog: [
      {
        id: 'audit-1',
        timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
        action: 'Created',
        performedBy: 'admin',
        details: 'Purchase order created from requisition',
        newStatus: 'draft'
      },
      {
        id: 'audit-2',
        timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
        action: 'Approved',
        performedBy: 'admin',
        details: 'PO approved for sending',
        previousStatus: 'draft',
        newStatus: 'approved'
      },
      {
        id: 'audit-3',
        timestamp: Date.now() - 1 * 24 * 60 * 60 * 1000,
        action: 'Emailed',
        performedBy: 'admin',
        details: 'PO sent to supplier@example.com',
        previousStatus: 'approved',
        newStatus: 'ordered'
      }
    ]
  },
  {
    id: 'po-2',
    poNumber: 'PO17345681MNOP',
    supplierId: 'sup-2',
    items: [
      {
        id: 'poitem-3',
        inventoryItemId: 'amenity-1',
        name: 'Shampoo Bottles',
        quantity: 100,
        unit: 'bottles',
        unitPrice: 3.75,
        total: 375
      }
    ],
    subtotal: 375,
    tax: 37.5,
    total: 412.5,
    status: 'approved',
    expectedDelivery: Date.now() + 5 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 6 * 60 * 60 * 1000,
    createdBy: 'admin',
    revisionNumber: 1,
    watermark: 'APPROVED',
    qrCode: 'QR-PO17345681MNOP',
    auditLog: [
      {
        id: 'audit-4',
        timestamp: Date.now() - 6 * 60 * 60 * 1000,
        action: 'Created',
        performedBy: 'admin',
        details: 'Purchase order created',
        newStatus: 'draft'
      }
    ]
  }
]

export const sampleGRNs: GoodsReceivedNote[] = [
  {
    id: 'grn-1',
    grnNumber: 'GRN17345682QRST',
    purchaseOrderId: 'po-3',
    supplierId: 'sup-1',
    items: [
      {
        id: 'grnitem-1',
        inventoryItemId: 'food-3',
        orderedQuantity: 100,
        receivedQuantity: 98,
        damagedQuantity: 2,
        batchNumber: 'BATCH2024-001',
        expiryDate: Date.now() + 30 * 24 * 60 * 60 * 1000,
        manufactureDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
        unitPrice: 4.50,
        varianceAmount: -9.00,
        varianceReason: 'Damaged during transport',
        barcode: '8901234567890',
        qualityStatus: 'good'
      }
    ],
    receivedAt: Date.now() - 12 * 60 * 60 * 1000,
    receivedBy: 'sophie_chen',
    invoiceNumber: 'INV-2024-001',
    invoiceAmount: 450.00,
    notes: '2 damaged items rejected, credit note requested',
    deliveryNoteNumber: 'DN-2024-001',
    vehicleNumber: 'ABC-1234',
    driverName: 'John Driver',
    hasVariance: true,
    varianceNotes: 'Supplier agreed to credit note for damaged items. Overall quality acceptable.',
    qualityCheckStatus: 'partial',
    invoicePhotos: [],
    deliveryNotePhotos: []
  }
]
